// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: comdex/liquidationsV2/v1beta1/liquidate.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LiquidationWhiteListing struct {
	AppId uint64 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty" yaml:"app_id"`
	//------------Auction Types defn
	// true auction type - "dutch"
	//false auction type - "english"
	AuctionType bool `protobuf:"varint,2,opt,name=auction_type,json=auctionType,proto3" json:"auction_type,omitempty" yaml:"auction_type"`
	//discount
	//upar kitna se start hoga
	Buffer github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=buffer,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"buffer" yaml:"buffer"`
	Cusp   github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=cusp,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"cusp" yaml:"cusp"`
	Step   github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,5,opt,name=step,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"step" yaml:"step"`
}

func (m *LiquidationWhiteListing) Reset()         { *m = LiquidationWhiteListing{} }
func (m *LiquidationWhiteListing) String() string { return proto.CompactTextString(m) }
func (*LiquidationWhiteListing) ProtoMessage()    {}
func (*LiquidationWhiteListing) Descriptor() ([]byte, []int) {
	return fileDescriptor_631048b9d11253bf, []int{0}
}
func (m *LiquidationWhiteListing) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LiquidationWhiteListing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LiquidationWhiteListing.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LiquidationWhiteListing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidationWhiteListing.Merge(m, src)
}
func (m *LiquidationWhiteListing) XXX_Size() int {
	return m.Size()
}
func (m *LiquidationWhiteListing) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidationWhiteListing.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidationWhiteListing proto.InternalMessageInfo

type LiquidationOffsetHolder struct {
	CurrentOffset uint64 `protobuf:"varint,2,opt,name=current_offset,json=currentOffset,proto3" json:"current_offset,omitempty"`
}

func (m *LiquidationOffsetHolder) Reset()         { *m = LiquidationOffsetHolder{} }
func (m *LiquidationOffsetHolder) String() string { return proto.CompactTextString(m) }
func (*LiquidationOffsetHolder) ProtoMessage()    {}
func (*LiquidationOffsetHolder) Descriptor() ([]byte, []int) {
	return fileDescriptor_631048b9d11253bf, []int{1}
}
func (m *LiquidationOffsetHolder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LiquidationOffsetHolder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LiquidationOffsetHolder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LiquidationOffsetHolder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidationOffsetHolder.Merge(m, src)
}
func (m *LiquidationOffsetHolder) XXX_Size() int {
	return m.Size()
}
func (m *LiquidationOffsetHolder) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidationOffsetHolder.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidationOffsetHolder proto.InternalMessageInfo

type LockedVault struct {
	LockedVaultId                uint64                                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" yaml:"id"`
	AppId                        uint64                                  `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty" yaml:"id"`
	OriginalVaultId              uint64                                  `protobuf:"varint,3,opt,name=original_vault_id,json=originalVaultId,proto3" json:"original_vault_id,omitempty" yaml:"id"`
	ExtendedPairId               uint64                                  `protobuf:"varint,4,opt,name=extended_pair_vault_id,json=extendedPairVaultId,proto3" json:"extended_pair_vault_id,omitempty" yaml:"extended_pair_vault_id"`
	Owner                        string                                  `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty" yaml:"owner"`
	CollateralToken              github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,6,opt,name=collateral_token,json=collateralToken,proto3,casttype=github.com/cosmos/cosmos-sdk/types.Coin" json:"collateral_token" yaml:"collateral_token"`
	DebtToken                    github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,7,opt,name=debt_token,json=debtToken,proto3,casttype=github.com/cosmos/cosmos-sdk/types.Coin" json:"debt_token" yaml:"debt_token"`
	CurrentCollaterlisationRatio github_com_cosmos_cosmos_sdk_types.Dec  `protobuf:"bytes,8,opt,name=current_collateralisation_ratio,json=currentCollateralisationRatio,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"current_collateralisation_ratio" yaml:"current_collateralisation_ratio"`
	CollateralToBeAuctioned      github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,9,opt,name=collateral_to_be_auctioned,json=collateralToBeAuctioned,proto3,casttype=github.com/cosmos/cosmos-sdk/types.Coin" json:"collateral_to_be_auctioned" yaml:"CollateralToBeAuctioned"`
	TargetDebt                   github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,10,opt,name=target_debt,json=targetDebt,proto3,casttype=github.com/cosmos/cosmos-sdk/types.Coin" json:"target_debt" yaml:"target_debt"`
	LiquidationTimestamp         time.Time                               `protobuf:"bytes,11,opt,name=liquidation_timestamp,json=liquidationTimestamp,proto3,stdtime" json:"liquidation_timestamp" yaml:"liquidation_timestamp"`
	IsInternalKeeper             bool                                    `protobuf:"varint,12,opt,name=is_internal_keeper,json=isInternalKeeper,proto3" json:"is_internal_keeper,omitempty" yaml:"is_intenal_keeper"`
	InternalKeeperAddress        string                                  `protobuf:"bytes,13,opt,name=internal_keeper_address,json=internalKeeperAddress,proto3" json:"internal_keeper_address,omitempty" yaml:"internal_keeper_address"`
	IsExternalKeeper             string                                  `protobuf:"bytes,14,opt,name=is_external_keeper,json=isExternalKeeper,proto3" json:"is_external_keeper,omitempty" yaml:"is_external_keeper"`
	ExternalKeeperAddress        string                                  `protobuf:"bytes,15,opt,name=external_keeper_address,json=externalKeeperAddress,proto3" json:"external_keeper_address,omitempty" yaml:"external_keeper_address"`
	FeeToBeCollected             github_com_cosmos_cosmos_sdk_types.Int  `protobuf:"bytes,16,opt,name=fee_to_be_collected,json=feeToBeCollected,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"fee_to_be_collected" yaml:"fee_to_be_collected"`
	InitiatorType                string                                  `protobuf:"bytes,17,opt,name=initiator_type,json=initiatorType,proto3" json:"initiator_type,omitempty" yaml:"initiator_type"`
	AuctionType                  bool                                    `protobuf:"varint,18,opt,name=auction_type,json=auctionType,proto3" json:"auction_type,omitempty" yaml:"auction_type"`
}

func (m *LockedVault) Reset()         { *m = LockedVault{} }
func (m *LockedVault) String() string { return proto.CompactTextString(m) }
func (*LockedVault) ProtoMessage()    {}
func (*LockedVault) Descriptor() ([]byte, []int) {
	return fileDescriptor_631048b9d11253bf, []int{2}
}
func (m *LockedVault) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LockedVault) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LockedVault.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LockedVault) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockedVault.Merge(m, src)
}
func (m *LockedVault) XXX_Size() int {
	return m.Size()
}
func (m *LockedVault) XXX_DiscardUnknown() {
	xxx_messageInfo_LockedVault.DiscardUnknown(m)
}

var xxx_messageInfo_LockedVault proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LiquidationWhiteListing)(nil), "comdex.liquidationsV2.v1beta1.LiquidationWhiteListing")
	proto.RegisterType((*LiquidationOffsetHolder)(nil), "comdex.liquidationsV2.v1beta1.LiquidationOffsetHolder")
	proto.RegisterType((*LockedVault)(nil), "comdex.liquidationsV2.v1beta1.LockedVault")
}

func init() {
	proto.RegisterFile("comdex/liquidationsV2/v1beta1/liquidate.proto", fileDescriptor_631048b9d11253bf)
}

var fileDescriptor_631048b9d11253bf = []byte{
	// 1079 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x4d, 0x6f, 0xe3, 0x44,
	0x18, 0x8e, 0x77, 0xdb, 0xb2, 0x9d, 0x6c, 0xbf, 0xa6, 0xed, 0xd6, 0x8d, 0xb6, 0x9e, 0xca, 0x12,
	0xa5, 0x42, 0xaa, 0x43, 0x77, 0x2f, 0x08, 0x84, 0xd8, 0xa6, 0x2d, 0x22, 0x50, 0xa9, 0xd4, 0xaa,
	0x76, 0xa5, 0x3d, 0x60, 0x1c, 0x7b, 0x92, 0x8e, 0xea, 0x78, 0x8c, 0x3d, 0x59, 0xda, 0x0b, 0x12,
	0xbf, 0x80, 0x72, 0xe1, 0x37, 0xc0, 0xbf, 0xe0, 0x58, 0x71, 0xda, 0x23, 0xe2, 0x60, 0xc0, 0xfd,
	0x07, 0x39, 0x72, 0x42, 0xf3, 0xe1, 0xd8, 0x49, 0xb3, 0x94, 0x70, 0x69, 0xea, 0x79, 0x9f, 0xe7,
	0x79, 0x9f, 0x77, 0xde, 0xf9, 0x02, 0x3b, 0x1e, 0xed, 0xfa, 0xf8, 0xa2, 0x1e, 0x90, 0xaf, 0x7b,
	0xc4, 0x77, 0x19, 0xa1, 0x61, 0xf2, 0xfc, 0x49, 0xfd, 0xd5, 0x6e, 0x0b, 0x33, 0x77, 0x77, 0x30,
	0x8c, 0xad, 0x28, 0xa6, 0x8c, 0xc2, 0x0d, 0x09, 0xb7, 0x86, 0xe1, 0x96, 0x82, 0xd7, 0x56, 0x3a,
	0xb4, 0x43, 0x05, 0xb2, 0xce, 0xff, 0x93, 0xa4, 0x1a, 0xea, 0x50, 0xda, 0x09, 0x70, 0x5d, 0x7c,
	0xb5, 0x7a, 0xed, 0x3a, 0x23, 0x5d, 0x9c, 0x30, 0xb7, 0x1b, 0x29, 0x80, 0xe1, 0xd1, 0xa4, 0x4b,
	0x93, 0x7a, 0xcb, 0x4d, 0xf0, 0x20, 0xb5, 0x47, 0x49, 0x28, 0xe3, 0xe6, 0x8f, 0xf7, 0xc1, 0xda,
	0x51, 0x91, 0xf1, 0xc5, 0x19, 0x61, 0xf8, 0x88, 0x24, 0x8c, 0x84, 0x1d, 0xb8, 0x0b, 0x66, 0xdc,
	0x28, 0x72, 0x88, 0xaf, 0x6b, 0x9b, 0xda, 0xf6, 0x54, 0xa3, 0x96, 0xa5, 0x68, 0x7a, 0x2f, 0x8a,
	0x9a, 0x7e, 0x3f, 0x45, 0x73, 0x97, 0x6e, 0x37, 0xf8, 0xc0, 0x94, 0x00, 0xd3, 0x9e, 0x76, 0xf9,
	0x38, 0x6c, 0x82, 0x87, 0x6e, 0xcf, 0xe3, 0x4a, 0x0e, 0xbb, 0x8c, 0xb0, 0x7e, 0x6f, 0x53, 0xdb,
	0x7e, 0xd0, 0xd8, 0xca, 0x52, 0x54, 0xdd, 0x93, 0xe3, 0xa7, 0x97, 0x11, 0xee, 0xa7, 0x68, 0x59,
	0xd1, 0x4b, 0x60, 0xd3, 0xae, 0xba, 0x05, 0x06, 0xbe, 0x00, 0x33, 0xad, 0x5e, 0xbb, 0x8d, 0x63,
	0xfd, 0xfe, 0xa6, 0xb6, 0x3d, 0xdb, 0xf8, 0xf8, 0x3a, 0x45, 0x95, 0xdf, 0x53, 0xb4, 0xd5, 0x21,
	0xec, 0xac, 0xd7, 0xb2, 0x3c, 0xda, 0xad, 0xab, 0xe2, 0xe4, 0xcf, 0x4e, 0xe2, 0x9f, 0xd7, 0xb9,
	0x50, 0x62, 0x1d, 0x60, 0xaf, 0xb0, 0x28, 0x55, 0x4c, 0x5b, 0xc9, 0xc1, 0x13, 0x30, 0xe5, 0xf5,
	0x92, 0x48, 0x9f, 0x12, 0xb2, 0x1f, 0x4d, 0x2c, 0x5b, 0x95, 0xb2, 0x5c, 0xc3, 0xb4, 0x85, 0x14,
	0x97, 0x4c, 0x18, 0x8e, 0xf4, 0xe9, 0x89, 0x25, 0x9b, 0x21, 0x2b, 0x24, 0xb9, 0x86, 0x69, 0x0b,
	0x29, 0xf3, 0xd9, 0x50, 0x5f, 0x8e, 0xdb, 0xed, 0x04, 0xb3, 0x4f, 0x69, 0xe0, 0xe3, 0x18, 0xbe,
	0x0d, 0xe6, 0xbd, 0x5e, 0x1c, 0xe3, 0x90, 0x39, 0x54, 0x8c, 0x8b, 0x69, 0x9e, 0xb2, 0xe7, 0xd4,
	0xa8, 0x04, 0x9b, 0xbf, 0x2e, 0x80, 0xea, 0x11, 0xf5, 0xce, 0xb1, 0xff, 0xdc, 0xed, 0x05, 0x0c,
	0x5a, 0xe0, 0xde, 0xa0, 0x95, 0x46, 0x96, 0xa2, 0xb9, 0x52, 0x50, 0xb4, 0x74, 0x56, 0xba, 0xe0,
	0xed, 0xbc, 0x47, 0x7c, 0xb8, 0x33, 0x68, 0xbf, 0x90, 0x6f, 0x3c, 0x2a, 0xb7, 0xbf, 0x84, 0x55,
	0xad, 0x3f, 0x02, 0x4b, 0x34, 0x26, 0x1d, 0x12, 0xba, 0x81, 0xf3, 0x8a, 0x6b, 0x72, 0xe6, 0x7d,
	0xc1, 0xdc, 0xcc, 0x52, 0xb4, 0x70, 0xac, 0x82, 0x63, 0xf3, 0x2d, 0xd0, 0xe1, 0x28, 0x3c, 0x03,
	0x8f, 0xf0, 0x05, 0xc3, 0xa1, 0x8f, 0x7d, 0x27, 0x72, 0x49, 0x5c, 0x48, 0x4e, 0x09, 0xc9, 0xa7,
	0x59, 0x8a, 0xe6, 0x0f, 0x15, 0xe2, 0x0b, 0x97, 0xc4, 0x42, 0x71, 0x43, 0x2a, 0x8e, 0x67, 0x9a,
	0xf6, 0x32, 0x2e, 0x11, 0xf2, 0x4c, 0x75, 0x30, 0x4d, 0xbf, 0x09, 0x71, 0xac, 0x9a, 0xb7, 0xce,
	0xab, 0x3c, 0xe6, 0x03, 0xfd, 0x14, 0x3d, 0x94, 0x7a, 0x22, 0x6e, 0xda, 0x12, 0x07, 0xaf, 0x34,
	0xb0, 0xe8, 0xd1, 0x20, 0x70, 0x19, 0x8e, 0xdd, 0xc0, 0x61, 0xf4, 0x1c, 0x87, 0xfa, 0xcc, 0xa6,
	0xb6, 0x5d, 0x7d, 0xb2, 0x6e, 0xc9, 0x06, 0x5b, 0x7c, 0xbb, 0xe5, 0x5b, 0xd7, 0xda, 0xa7, 0x24,
	0x6c, 0x7c, 0xc6, 0x17, 0x45, 0x3f, 0x45, 0x6b, 0x6a, 0xf5, 0x8c, 0x08, 0x98, 0x7f, 0xa7, 0xe8,
	0x9d, 0xff, 0xb0, 0x5e, 0xb8, 0x96, 0xbd, 0x50, 0xb0, 0x4f, 0x39, 0x19, 0x7e, 0x0b, 0x80, 0x8f,
	0x5b, 0x4c, 0x79, 0x79, 0xeb, 0x2e, 0x2f, 0x07, 0xca, 0xcb, 0x92, 0xf4, 0x52, 0x50, 0x27, 0x72,
	0x31, 0xcb, 0x79, 0x32, 0xff, 0x2f, 0x1a, 0x40, 0xf9, 0x92, 0x2c, 0xbc, 0x91, 0x44, 0xac, 0x5d,
	0x27, 0xe6, 0x3f, 0xfa, 0x03, 0x31, 0xbd, 0x17, 0x93, 0x6d, 0xb7, 0x2c, 0x45, 0x8f, 0xf7, 0xa5,
	0xf0, 0xbe, 0xd2, 0xcd, 0x65, 0x6d, 0xfe, 0xb7, 0x9f, 0xa2, 0xad, 0x7c, 0x3b, 0xfe, 0x6b, 0x7a,
	0xd3, 0xde, 0xf0, 0x86, 0x75, 0xdc, 0x21, 0x21, 0xf8, 0xb3, 0x06, 0x6a, 0x43, 0x4d, 0x71, 0x5a,
	0xd8, 0x51, 0xe7, 0x11, 0xf6, 0xf5, 0xd9, 0xbb, 0xe6, 0xf4, 0x44, 0xcd, 0xa9, 0x21, 0xed, 0xec,
	0x97, 0x3a, 0xd4, 0xc0, 0x7b, 0xb9, 0xce, 0x44, 0x13, 0xbc, 0xe6, 0x8d, 0x17, 0x81, 0xdf, 0x69,
	0xa0, 0xca, 0xdc, 0xb8, 0x83, 0x99, 0xc3, 0x7b, 0xa0, 0x83, 0xbb, 0xcc, 0x1d, 0x2a, 0x73, 0x50,
	0x9a, 0x2b, 0x71, 0x27, 0x32, 0x04, 0x24, 0xf1, 0x00, 0xb7, 0x18, 0xfc, 0x41, 0x03, 0xab, 0xa5,
	0xab, 0xca, 0x19, 0x5c, 0x3c, 0x7a, 0x55, 0xb8, 0xa9, 0x59, 0xf2, 0x6a, 0xb2, 0xf2, 0xab, 0xc9,
	0x3a, 0xcd, 0x11, 0x8d, 0x67, 0xdc, 0x4e, 0x96, 0xa2, 0x95, 0xd2, 0x09, 0x37, 0x88, 0xf6, 0x53,
	0xf4, 0x58, 0xda, 0x1c, 0x2b, 0x6f, 0x5e, 0xfd, 0x81, 0x34, 0x7b, 0x25, 0x18, 0xc3, 0x84, 0x5f,
	0x02, 0x48, 0x12, 0x87, 0x84, 0x0c, 0xc7, 0xfc, 0x14, 0x3a, 0xc7, 0x38, 0xc2, 0xb1, 0xfe, 0x50,
	0xdc, 0x41, 0xef, 0x65, 0x29, 0x5a, 0x6c, 0x26, 0x4d, 0x15, 0xfc, 0x5c, 0xc4, 0xfa, 0x29, 0xd2,
	0xd5, 0x21, 0x24, 0x79, 0x05, 0xcd, 0xb4, 0x17, 0xc9, 0x08, 0x1a, 0x26, 0x60, 0x6d, 0x44, 0xdc,
	0x71, 0x7d, 0x3f, 0xc6, 0x49, 0xa2, 0xcf, 0x89, 0xd5, 0xfd, 0x61, 0x96, 0xa2, 0xd5, 0x61, 0xd2,
	0x9e, 0x04, 0x14, 0x2b, 0xe3, 0x0d, 0x0a, 0xa6, 0xbd, 0x4a, 0xc6, 0x11, 0xa1, 0x23, 0x8a, 0xe2,
	0x27, 0x57, 0xb9, 0xa8, 0x79, 0x91, 0x6f, 0x57, 0x16, 0x75, 0x78, 0x31, 0x52, 0xd4, 0xfa, 0xa0,
	0xa8, 0x11, 0x9e, 0xa8, 0x6a, 0x18, 0xce, 0xab, 0x1a, 0x41, 0x0d, 0xaa, 0x5a, 0x28, 0xaa, 0x1a,
	0x26, 0xdd, 0xaa, 0xea, 0x0d, 0x0a, 0xa6, 0xbd, 0x8a, 0xc7, 0x11, 0xe1, 0xf7, 0x1a, 0x58, 0x6e,
	0x63, 0xac, 0xf6, 0x19, 0x5f, 0xe8, 0xd8, 0x63, 0xd8, 0xd7, 0x17, 0x45, 0xc6, 0xaf, 0x26, 0xbb,
	0x41, 0xf9, 0x2c, 0x7c, 0x82, 0x31, 0xdf, 0x24, 0xfb, 0xb9, 0x52, 0x3f, 0x45, 0x35, 0x69, 0x6d,
	0x4c, 0x1a, 0xd3, 0x5e, 0x6c, 0x8f, 0xe0, 0xe1, 0x09, 0x98, 0x27, 0x21, 0x61, 0xc4, 0x65, 0x34,
	0x96, 0x8f, 0x97, 0x25, 0xe1, 0xe5, 0x5d, 0x7e, 0x55, 0x36, 0xf3, 0x88, 0x7a, 0xbe, 0xac, 0xe6,
	0xbd, 0x2c, 0x13, 0x4c, 0x7b, 0x8e, 0x94, 0x71, 0xb7, 0x5e, 0x43, 0xf0, 0x7f, 0xbf, 0x86, 0x1a,
	0x2f, 0xaf, 0xff, 0x32, 0x2a, 0x3f, 0x65, 0x46, 0xe5, 0x3a, 0x33, 0xb4, 0xd7, 0x99, 0xa1, 0xfd,
	0x99, 0x19, 0xda, 0xd5, 0x8d, 0x51, 0x79, 0x7d, 0x63, 0x54, 0x7e, 0xbb, 0x31, 0x2a, 0x2f, 0xdf,
	0x1f, 0x9a, 0x2b, 0xfe, 0x94, 0xdc, 0xa1, 0xed, 0x36, 0xf1, 0x88, 0x1b, 0xa8, 0xef, 0xfa, 0xad,
	0xb7, 0xa8, 0x98, 0xc1, 0xd6, 0x8c, 0xd8, 0xa2, 0x4f, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x91,
	0xbf, 0x95, 0x9e, 0xb1, 0x0a, 0x00, 0x00,
}

func (m *LiquidationWhiteListing) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LiquidationWhiteListing) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LiquidationWhiteListing) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Step.Size()
		i -= size
		if _, err := m.Step.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidate(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.Cusp.Size()
		i -= size
		if _, err := m.Cusp.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidate(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.Buffer.Size()
		i -= size
		if _, err := m.Buffer.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidate(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.AuctionType {
		i--
		if m.AuctionType {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.AppId != 0 {
		i = encodeVarintLiquidate(dAtA, i, uint64(m.AppId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *LiquidationOffsetHolder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LiquidationOffsetHolder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LiquidationOffsetHolder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CurrentOffset != 0 {
		i = encodeVarintLiquidate(dAtA, i, uint64(m.CurrentOffset))
		i--
		dAtA[i] = 0x10
	}
	return len(dAtA) - i, nil
}

func (m *LockedVault) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LockedVault) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LockedVault) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AuctionType {
		i--
		if m.AuctionType {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if len(m.InitiatorType) > 0 {
		i -= len(m.InitiatorType)
		copy(dAtA[i:], m.InitiatorType)
		i = encodeVarintLiquidate(dAtA, i, uint64(len(m.InitiatorType)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	{
		size := m.FeeToBeCollected.Size()
		i -= size
		if _, err := m.FeeToBeCollected.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidate(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0x82
	if len(m.ExternalKeeperAddress) > 0 {
		i -= len(m.ExternalKeeperAddress)
		copy(dAtA[i:], m.ExternalKeeperAddress)
		i = encodeVarintLiquidate(dAtA, i, uint64(len(m.ExternalKeeperAddress)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.IsExternalKeeper) > 0 {
		i -= len(m.IsExternalKeeper)
		copy(dAtA[i:], m.IsExternalKeeper)
		i = encodeVarintLiquidate(dAtA, i, uint64(len(m.IsExternalKeeper)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.InternalKeeperAddress) > 0 {
		i -= len(m.InternalKeeperAddress)
		copy(dAtA[i:], m.InternalKeeperAddress)
		i = encodeVarintLiquidate(dAtA, i, uint64(len(m.InternalKeeperAddress)))
		i--
		dAtA[i] = 0x6a
	}
	if m.IsInternalKeeper {
		i--
		if m.IsInternalKeeper {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x60
	}
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.LiquidationTimestamp, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.LiquidationTimestamp):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintLiquidate(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x5a
	{
		size, err := m.TargetDebt.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLiquidate(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	{
		size, err := m.CollateralToBeAuctioned.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLiquidate(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	{
		size := m.CurrentCollaterlisationRatio.Size()
		i -= size
		if _, err := m.CurrentCollaterlisationRatio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidate(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size, err := m.DebtToken.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLiquidate(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size, err := m.CollateralToken.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLiquidate(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintLiquidate(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x2a
	}
	if m.ExtendedPairId != 0 {
		i = encodeVarintLiquidate(dAtA, i, uint64(m.ExtendedPairId))
		i--
		dAtA[i] = 0x20
	}
	if m.OriginalVaultId != 0 {
		i = encodeVarintLiquidate(dAtA, i, uint64(m.OriginalVaultId))
		i--
		dAtA[i] = 0x18
	}
	if m.AppId != 0 {
		i = encodeVarintLiquidate(dAtA, i, uint64(m.AppId))
		i--
		dAtA[i] = 0x10
	}
	if m.LockedVaultId != 0 {
		i = encodeVarintLiquidate(dAtA, i, uint64(m.LockedVaultId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintLiquidate(dAtA []byte, offset int, v uint64) int {
	offset -= sovLiquidate(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LiquidationWhiteListing) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AppId != 0 {
		n += 1 + sovLiquidate(uint64(m.AppId))
	}
	if m.AuctionType {
		n += 2
	}
	l = m.Buffer.Size()
	n += 1 + l + sovLiquidate(uint64(l))
	l = m.Cusp.Size()
	n += 1 + l + sovLiquidate(uint64(l))
	l = m.Step.Size()
	n += 1 + l + sovLiquidate(uint64(l))
	return n
}

func (m *LiquidationOffsetHolder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CurrentOffset != 0 {
		n += 1 + sovLiquidate(uint64(m.CurrentOffset))
	}
	return n
}

func (m *LockedVault) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LockedVaultId != 0 {
		n += 1 + sovLiquidate(uint64(m.LockedVaultId))
	}
	if m.AppId != 0 {
		n += 1 + sovLiquidate(uint64(m.AppId))
	}
	if m.OriginalVaultId != 0 {
		n += 1 + sovLiquidate(uint64(m.OriginalVaultId))
	}
	if m.ExtendedPairId != 0 {
		n += 1 + sovLiquidate(uint64(m.ExtendedPairId))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovLiquidate(uint64(l))
	}
	l = m.CollateralToken.Size()
	n += 1 + l + sovLiquidate(uint64(l))
	l = m.DebtToken.Size()
	n += 1 + l + sovLiquidate(uint64(l))
	l = m.CurrentCollaterlisationRatio.Size()
	n += 1 + l + sovLiquidate(uint64(l))
	l = m.CollateralToBeAuctioned.Size()
	n += 1 + l + sovLiquidate(uint64(l))
	l = m.TargetDebt.Size()
	n += 1 + l + sovLiquidate(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.LiquidationTimestamp)
	n += 1 + l + sovLiquidate(uint64(l))
	if m.IsInternalKeeper {
		n += 2
	}
	l = len(m.InternalKeeperAddress)
	if l > 0 {
		n += 1 + l + sovLiquidate(uint64(l))
	}
	l = len(m.IsExternalKeeper)
	if l > 0 {
		n += 1 + l + sovLiquidate(uint64(l))
	}
	l = len(m.ExternalKeeperAddress)
	if l > 0 {
		n += 1 + l + sovLiquidate(uint64(l))
	}
	l = m.FeeToBeCollected.Size()
	n += 2 + l + sovLiquidate(uint64(l))
	l = len(m.InitiatorType)
	if l > 0 {
		n += 2 + l + sovLiquidate(uint64(l))
	}
	if m.AuctionType {
		n += 3
	}
	return n
}

func sovLiquidate(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLiquidate(x uint64) (n int) {
	return sovLiquidate(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LiquidationWhiteListing) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidate
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LiquidationWhiteListing: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LiquidationWhiteListing: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			m.AppId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionType", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AuctionType = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buffer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Buffer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cusp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Cusp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Step", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Step.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidate(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiquidate
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LiquidationOffsetHolder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidate
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LiquidationOffsetHolder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LiquidationOffsetHolder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentOffset", wireType)
			}
			m.CurrentOffset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentOffset |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidate(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiquidate
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LockedVault) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidate
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LockedVault: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LockedVault: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockedVaultId", wireType)
			}
			m.LockedVaultId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LockedVaultId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			m.AppId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OriginalVaultId", wireType)
			}
			m.OriginalVaultId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OriginalVaultId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtendedPairId", wireType)
			}
			m.ExtendedPairId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExtendedPairId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralToken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidate
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CollateralToken.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DebtToken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidate
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DebtToken.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentCollaterlisationRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CurrentCollaterlisationRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralToBeAuctioned", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidate
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CollateralToBeAuctioned.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetDebt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidate
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TargetDebt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationTimestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidate
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.LiquidationTimestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsInternalKeeper", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsInternalKeeper = bool(v != 0)
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InternalKeeperAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InternalKeeperAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsExternalKeeper", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IsExternalKeeper = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExternalKeeperAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExternalKeeperAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeToBeCollected", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FeeToBeCollected.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitiatorType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InitiatorType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionType", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AuctionType = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidate(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiquidate
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLiquidate(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLiquidate
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLiquidate
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLiquidate
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLiquidate
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLiquidate
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLiquidate        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLiquidate          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLiquidate = fmt.Errorf("proto: unexpected end of group")
)
