// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: comdex/liquidationsV2/v1beta1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgLiquidateInternalKeeperRequest struct {
	From    string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty" yaml:"from"`
	LiqType uint64 `protobuf:"varint,2,opt,name=liq_type,json=liqType,proto3" json:"liq_type,omitempty" yaml:"liq_type"`
	Id      uint64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty" yaml:"id"`
}

func (m *MsgLiquidateInternalKeeperRequest) Reset()         { *m = MsgLiquidateInternalKeeperRequest{} }
func (m *MsgLiquidateInternalKeeperRequest) String() string { return proto.CompactTextString(m) }
func (*MsgLiquidateInternalKeeperRequest) ProtoMessage()    {}
func (*MsgLiquidateInternalKeeperRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51c735c845851e88, []int{0}
}
func (m *MsgLiquidateInternalKeeperRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLiquidateInternalKeeperRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLiquidateInternalKeeperRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLiquidateInternalKeeperRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLiquidateInternalKeeperRequest.Merge(m, src)
}
func (m *MsgLiquidateInternalKeeperRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgLiquidateInternalKeeperRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLiquidateInternalKeeperRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLiquidateInternalKeeperRequest proto.InternalMessageInfo

type MsgLiquidateInternalKeeperResponse struct {
}

func (m *MsgLiquidateInternalKeeperResponse) Reset()         { *m = MsgLiquidateInternalKeeperResponse{} }
func (m *MsgLiquidateInternalKeeperResponse) String() string { return proto.CompactTextString(m) }
func (*MsgLiquidateInternalKeeperResponse) ProtoMessage()    {}
func (*MsgLiquidateInternalKeeperResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51c735c845851e88, []int{1}
}
func (m *MsgLiquidateInternalKeeperResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLiquidateInternalKeeperResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLiquidateInternalKeeperResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLiquidateInternalKeeperResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLiquidateInternalKeeperResponse.Merge(m, src)
}
func (m *MsgLiquidateInternalKeeperResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgLiquidateInternalKeeperResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLiquidateInternalKeeperResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLiquidateInternalKeeperResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgLiquidateInternalKeeperRequest)(nil), "comdex.liquidationsV2.v1beta1.MsgLiquidateInternalKeeperRequest")
	proto.RegisterType((*MsgLiquidateInternalKeeperResponse)(nil), "comdex.liquidationsV2.v1beta1.MsgLiquidateInternalKeeperResponse")
}

func init() {
	proto.RegisterFile("comdex/liquidationsV2/v1beta1/tx.proto", fileDescriptor_51c735c845851e88)
}

var fileDescriptor_51c735c845851e88 = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x3f, 0x8e, 0x9b, 0x40,
	0x18, 0xc5, 0x19, 0x6c, 0xc5, 0xf1, 0xa4, 0xb0, 0x44, 0x52, 0x58, 0x48, 0x19, 0x1c, 0x1c, 0x45,
	0x6e, 0xc2, 0xc8, 0x4e, 0x93, 0xa4, 0x4a, 0xdc, 0x59, 0xb1, 0x1b, 0x14, 0xa5, 0x70, 0x13, 0xf1,
	0x67, 0x20, 0x23, 0x01, 0x03, 0xcc, 0x10, 0xd9, 0xb7, 0xc8, 0x15, 0xd2, 0x79, 0x6f, 0xe2, 0xd2,
	0xe5, 0x56, 0x68, 0x17, 0xdf, 0xc0, 0x27, 0x58, 0xc1, 0xb0, 0x2b, 0xad, 0x56, 0xeb, 0x2d, 0xb6,
	0xe3, 0xe3, 0xfd, 0xde, 0xbc, 0x4f, 0x6f, 0x06, 0x7e, 0xf0, 0x58, 0xec, 0x93, 0x0d, 0x8e, 0x68,
	0x56, 0x50, 0xdf, 0x11, 0x94, 0x25, 0xfc, 0xd7, 0x0c, 0xff, 0x9d, 0xba, 0x44, 0x38, 0x53, 0x2c,
	0x36, 0x56, 0x9a, 0x33, 0xc1, 0xb4, 0xb7, 0x92, 0xb3, 0xee, 0x73, 0x56, 0xcb, 0xe9, 0x6f, 0x42,
	0x16, 0xb2, 0x86, 0xc4, 0xf5, 0x97, 0x34, 0xe9, 0x46, 0xc8, 0x58, 0x18, 0x11, 0xdc, 0x4c, 0x6e,
	0x11, 0x60, 0x41, 0x63, 0xc2, 0x85, 0x13, 0xa7, 0x2d, 0x80, 0x3c, 0xc6, 0x63, 0xc6, 0xb1, 0xeb,
	0x70, 0x72, 0x97, 0xe9, 0x31, 0x9a, 0x48, 0xdd, 0xdc, 0x01, 0xf8, 0x6e, 0xc5, 0xc3, 0x65, 0x1b,
	0x4a, 0x16, 0x89, 0x20, 0x79, 0xe2, 0x44, 0x3f, 0x08, 0x49, 0x49, 0x6e, 0x93, 0xac, 0x20, 0x5c,
	0x68, 0x63, 0xd8, 0x0d, 0x72, 0x16, 0x0f, 0xc1, 0x08, 0x4c, 0xfa, 0xf3, 0xc1, 0xa9, 0x34, 0x5e,
	0x6d, 0x9d, 0x38, 0xfa, 0x6a, 0xd6, 0x7f, 0x4d, 0xbb, 0x11, 0xb5, 0x2f, 0xf0, 0x65, 0x44, 0xb3,
	0xdf, 0x62, 0x9b, 0x92, 0xa1, 0x3a, 0x02, 0x93, 0xee, 0x1c, 0x55, 0xa5, 0xd1, 0x5b, 0xd2, 0xec,
	0xe7, 0x36, 0x25, 0xa7, 0xd2, 0x18, 0x48, 0xcf, 0x2d, 0x64, 0xda, 0xbd, 0x48, 0x6a, 0xda, 0x18,
	0xaa, 0xd4, 0x1f, 0x76, 0x1a, 0xd3, 0xeb, 0xaa, 0x34, 0xd4, 0x85, 0x7f, 0x2a, 0x8d, 0xbe, 0xe4,
	0xa9, 0x6f, 0xda, 0x2a, 0xf5, 0xcd, 0xf7, 0xd0, 0x3c, 0xb7, 0x29, 0x4f, 0x59, 0xc2, 0xc9, 0xec,
	0x02, 0xc0, 0xce, 0x8a, 0x87, 0xda, 0x7f, 0x00, 0xf5, 0xc7, 0x71, 0xed, 0x9b, 0x75, 0xb6, 0x6e,
	0xeb, 0xc9, 0x4e, 0xf4, 0xef, 0xcf, 0x38, 0x41, 0xee, 0x3a, 0x5f, 0xef, 0xaf, 0x91, 0xb2, 0xab,
	0x90, 0xb2, 0xaf, 0x10, 0x38, 0x54, 0x08, 0x5c, 0x55, 0x08, 0xfc, 0x3b, 0x22, 0xe5, 0x70, 0x44,
	0xca, 0xe5, 0x11, 0x29, 0xeb, 0xcf, 0x21, 0x15, 0x7f, 0x0a, 0xb7, 0x8e, 0xc2, 0x32, 0xee, 0x23,
	0x0b, 0x02, 0xea, 0x51, 0x27, 0x6a, 0x67, 0xfc, 0xe0, 0x65, 0xd5, 0xdd, 0x72, 0xf7, 0x45, 0x73,
	0xbf, 0x9f, 0x6e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x38, 0x0d, 0x9d, 0x54, 0x7f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	MsgLiquidateInternalKeeper(ctx context.Context, in *MsgLiquidateInternalKeeperRequest, opts ...grpc.CallOption) (*MsgLiquidateInternalKeeperResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) MsgLiquidateInternalKeeper(ctx context.Context, in *MsgLiquidateInternalKeeperRequest, opts ...grpc.CallOption) (*MsgLiquidateInternalKeeperResponse, error) {
	out := new(MsgLiquidateInternalKeeperResponse)
	err := c.cc.Invoke(ctx, "/comdex.liquidationsV2.v1beta1.Msg/MsgLiquidateInternalKeeper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	MsgLiquidateInternalKeeper(context.Context, *MsgLiquidateInternalKeeperRequest) (*MsgLiquidateInternalKeeperResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) MsgLiquidateInternalKeeper(ctx context.Context, req *MsgLiquidateInternalKeeperRequest) (*MsgLiquidateInternalKeeperResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MsgLiquidateInternalKeeper not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_MsgLiquidateInternalKeeper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgLiquidateInternalKeeperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MsgLiquidateInternalKeeper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comdex.liquidationsV2.v1beta1.Msg/MsgLiquidateInternalKeeper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MsgLiquidateInternalKeeper(ctx, req.(*MsgLiquidateInternalKeeperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "comdex.liquidationsV2.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MsgLiquidateInternalKeeper",
			Handler:    _Msg_MsgLiquidateInternalKeeper_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comdex/liquidationsV2/v1beta1/tx.proto",
}

func (m *MsgLiquidateInternalKeeperRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLiquidateInternalKeeperRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLiquidateInternalKeeperRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x18
	}
	if m.LiqType != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.LiqType))
		i--
		dAtA[i] = 0x10
	}
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintTx(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgLiquidateInternalKeeperResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLiquidateInternalKeeperResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLiquidateInternalKeeperResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgLiquidateInternalKeeperRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.LiqType != 0 {
		n += 1 + sovTx(uint64(m.LiqType))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgLiquidateInternalKeeperResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgLiquidateInternalKeeperRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLiquidateInternalKeeperRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLiquidateInternalKeeperRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiqType", wireType)
			}
			m.LiqType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LiqType |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgLiquidateInternalKeeperResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLiquidateInternalKeeperResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLiquidateInternalKeeperResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
