chains:
  - name: comdex-1
    type: custom
    numValidators: 2
    image: anmol1696/comdex:latest
    home: /root/.comdex
    binary: comdex
    prefix: comdex
    denom: ucmdx
    coins: 100000000000000ucmdx,100000000000000uharbor,100000000000000ucmst
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/comdex-official/comdex
    ports:
      rest: 1317
      rpc: 26657
      faucet: 8007
  - name: gaia-1
    type: cosmos
    numValidators: 1
    ports:
      rest: 1313
      rpc: 26653
      faucet: 8003

relayers:
  - name: comdex-gaia
    type: hermes
    replicas: 1
    chains:
      - comdex-1
      - gaia-1

registry:
  enabled: true
  ports:
    rest: 8081

explorer:
  enabled: true
  ports:
    rest: 8080