package types

import (
	errorsmod "cosmossdk.io/errors"
)

var (
	ErrorInvalidDecimals                   = errorsmod.Register(ModuleName, 101, "invalid decimals")
	ErrorInvalidDenom                      = errorsmod.Register(ModuleName, 102, "invalid denom")
	ErrorInvalidFrom                       = errorsmod.Register(ModuleName, 103, "invalid from")
	ErrorInvalidRecipient                  = errorsmod.Register(ModuleName, 104, "invalid recipient address")
	ErrorInvalidID                         = errorsmod.Register(ModuleName, 105, "invalid id")
	ErrorInvalidName                       = errorsmod.Register(ModuleName, 106, "invalid name")
	ErrorInvalidGenesisSupply              = errorsmod.Register(ModuleName, 107, "invalid Genesis Supply")
	ErrorInvalidMinGovSupply               = errorsmod.Register(ModuleName, 108, "invalid min gov supply")
	ErrorAssetDoesNotExist                 = errorsmod.Register(ModuleName, 109, "asset does not exist")
	ErrorDuplicateAsset                    = errorsmod.Register(ModuleName, 110, "duplicate asset")
	ErrorPairDoesNotExist                  = errorsmod.Register(ModuleName, 111, "pair does not exist")
	ErrorDuplicatePair                     = errorsmod.Register(ModuleName, 112, "duplicate pair")
	ErrorDuplicateApp                      = errorsmod.Register(ModuleName, 113, "duplicate app")
	ErrorPairNameForID                     = errorsmod.Register(ModuleName, 114, "already has pair name for id in this app")
	AppIdsDoesntExist                      = errorsmod.Register(ModuleName, 115, "app ids does not exist")
	ErrorAssetAlreadyExistingApp           = errorsmod.Register(ModuleName, 116, "asset already exist in App")
	ErrorAssetIsOffChain                   = errorsmod.Register(ModuleName, 117, "asset has been marked off chain")
	ErrorDebtFloorIsGreaterThanDebtCeiling = errorsmod.Register(ModuleName, 118, "Debt Floor Is Greater Than Debt Ceiling")
	ErrorGenesisTokenExistForApp           = errorsmod.Register(ModuleName, 119, "Genesis Token already Exist For App")
	ErrorFeeShouldNotBeGTOne               = errorsmod.Register(ModuleName, 120, "Fee Should Not Be Greater than One and less than zero")
	ErrorExtendedPairDoesNotExistForTheApp = errorsmod.Register(ModuleName, 121, "extended pair does not exist for the app")
	ErrorMinGovDepositIsZero               = errorsmod.Register(ModuleName, 122, "min gov deposit is zero")
	ErrorShortNameDidNotMeetCriterion      = errorsmod.Register(ModuleName, 123, "App ShortName didn't meet the criterion")
	ErrorNameDidNotMeetCriterion           = errorsmod.Register(ModuleName, 124, "Asset Name didn't meet the criterion")
	ErrorReversePairAlreadyExist           = errorsmod.Register(ModuleName, 125, "Reverse pair already exists")
	ErrorValueCantBeNegative               = errorsmod.Register(ModuleName, 126, "Value can't be negative")
	ErrorAppNameDidNotMeetCriterion        = errorsmod.Register(ModuleName, 127, "App Name didn't meet the criterion")
	ErrorPairNameDidNotMeetCriterion       = errorsmod.Register(ModuleName, 128, "Pair Name didn't meet the criterion")
	ErrorDuplicateShortNameForApp          = errorsmod.Register(ModuleName, 129, "duplicate short name for app")
	ErrorIsCDPMintableDisabled             = errorsmod.Register(ModuleName, 130, "can not use asset out for which cdp mintable is false")
	ErrorMinGovDepositShouldBeZero         = errorsmod.Register(ModuleName, 131, "min gov deposit should be zero if token not used for governance")
	ErrorOffChainAssetCannotBeMintable     = errorsmod.Register(ModuleName, 132, "Off Chain Asset Can not Be Mintable")
	ErrorUnknownProposalType               = errorsmod.Register(ModuleName, 133, "unknown proposal type")
	ErrorEmptyProposalAssets               = errorsmod.Register(ModuleName, 134, "empty assets in proposal")
	ErrorUnknownAppType                    = errorsmod.Register(ModuleName, 135, "unknown app type")
	ErrorProposalTitleMissing              = errorsmod.Register(ModuleName, 136, "proposal title missing")
	ErrorProposalDescriptionMissing        = errorsmod.Register(ModuleName, 137, "proposal description missing")
)
