package types

import (
	"github.com/cosmos/cosmos-sdk/types/errors"
)

var (
	ErrorInvalidDecimals                   = errors.Register(ModuleName, 101, "invalid decimals")
	ErrorInvalidDenom                      = errors.Register(ModuleName, 102, "invalid denom")
	ErrorInvalidFrom                       = errors.Register(ModuleName, 103, "invalid from")
	ErrorInvalidRecipient                  = errors.Register(ModuleName, 104, "invalid recipient address")
	ErrorInvalidID                         = errors.Register(ModuleName, 105, "invalid id")
	ErrorInvalidName                       = errors.Register(ModuleName, 106, "invalid name")
	ErrorInvalidGenesisSupply              = errors.Register(ModuleName, 107, "invalid Genesis Supply")
	ErrorInvalidMinGovSupply               = errors.Register(ModuleName, 108, "invalid min gov supply")
	ErrorAssetDoesNotExist                 = errors.Register(ModuleName, 109, "asset does not exist")
	ErrorDuplicateAsset                    = errors.Register(ModuleName, 110, "duplicate asset")
	ErrorPairDoesNotExist                  = errors.Register(ModuleName, 111, "pair does not exist")
	ErrorDuplicatePair                     = errors.Register(ModuleName, 112, "duplicate pair")
	ErrorDuplicateApp                      = errors.Register(ModuleName, 113, "duplicate app")
	ErrorPairNameForID                     = errors.Register(ModuleName, 114, "already has pair name for id in this app")
	AppIdsDoesntExist                      = errors.Register(ModuleName, 115, "app ids does not exist")
	ErrorAssetAlreadyExistingApp           = errors.Register(ModuleName, 116, "asset already exist in App")
	ErrorAssetIsOffChain                   = errors.Register(ModuleName, 117, "asset has been marked off chain")
	ErrorDebtFloorIsGreaterThanDebtCeiling = errors.Register(ModuleName, 118, "Debt Floor Is Greater Than Debt Ceiling")
	ErrorGenesisTokenExistForApp           = errors.Register(ModuleName, 119, "Genesis Token already Exist For App")
	ErrorFeeShouldNotBeGTOne               = errors.Register(ModuleName, 120, "Fee Should Not Be Greater than One and less than zero")
	ErrorExtendedPairDoesNotExistForTheApp = errors.Register(ModuleName, 121, "extended pair does not exist for the app")
	ErrorMinGovDepositIsZero               = errors.Register(ModuleName, 122, "min gov deposit is zero")
	ErrorShortNameDidNotMeetCriterion      = errors.Register(ModuleName, 123, "App ShortName didn't meet the criterion")
	ErrorNameDidNotMeetCriterion           = errors.Register(ModuleName, 124, "Asset Name didn't meet the criterion")
	ErrorReversePairAlreadyExist           = errors.Register(ModuleName, 125, "Reverse pair already exists")
	ErrorValueCantBeNegative               = errors.Register(ModuleName, 126, "Value can't be negative")
	ErrorAppNameDidNotMeetCriterion        = errors.Register(ModuleName, 127, "App Name didn't meet the criterion")
	ErrorPairNameDidNotMeetCriterion       = errors.Register(ModuleName, 128, "Pair Name didn't meet the criterion")
	ErrorDuplicateShortNameForApp          = errors.Register(ModuleName, 129, "duplicate short name for app")
	ErrorIsCDPMintableDisabled             = errors.Register(ModuleName, 130, "can not use asset out for which cdp mintable is false")
	ErrorMinGovDepositShouldBeZero         = errors.Register(ModuleName, 131, "min gov deposit should be zero if token not used for governance")
	ErrorOffChainAssetCannotBeMintable     = errors.Register(ModuleName, 132, "Off Chain Asset Can not Be Mintable")
	ErrorUnknownProposalType               = errors.Register(ModuleName, 133, "unknown proposal type")
	ErrorEmptyProposalAssets               = errors.Register(ModuleName, 134, "empty assets in proposal")
	ErrorUnknownAppType                    = errors.Register(ModuleName, 135, "unknown app type")
	ErrorProposalTitleMissing              = errors.Register(ModuleName, 136, "proposal title missing")
	ErrorProposalDescriptionMissing        = errors.Register(ModuleName, 137, "proposal description missing")
)
