// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: comdex/auctionsV2/v1beta1/auction.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Auctions struct {
	AuctionId       uint64                                  `protobuf:"varint,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty" yaml:"auction_id"`
	CollateralToken github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,2,opt,name=collateral_token,json=collateralToken,proto3,casttype=github.com/cosmos/cosmos-sdk/types.Coin" json:"collateral_token" yaml:"collateral_token"`
	// cosmos.base.v1beta1.Coin outflow_token_current_amount = 3 [
	//   (gogoproto.nullable) = false,
	//   (gogoproto.moretags) = "yaml:\"outflow_token_current_amount\"",
	//   (gogoproto.casttype) = "github.com/cosmos/cosmos-sdk/types.Coin"
	// ];
	DebtToken github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,3,opt,name=debt_token,json=debtToken,proto3,casttype=github.com/cosmos/cosmos-sdk/types.Coin" json:"debt_token" yaml:"inflow_token_target_amount"`
	// cosmos.base.v1beta1.Coin inflow_token_current_amount = 5 [
	//   (gogoproto.nullable) = false,
	//   (gogoproto.moretags) = "yaml:\"inflow_token_current_amount\"",
	//   (gogoproto.casttype) = "github.com/cosmos/cosmos-sdk/types.Coin"
	// ];
	ActiveBiddingId uint64                                 `protobuf:"varint,4,opt,name=active_bidding_id,json=activeBiddingId,proto3" json:"active_bidding_id,omitempty" yaml:"active_bidding_id"`
	BiddingIds      []*BidOwnerMapping                     `protobuf:"bytes,5,rep,name=bidding_ids,json=biddingIds,proto3" json:"bidding_ids,omitempty" yaml:"bidding_ids"`
	BidFactor       github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,6,opt,name=bid_factor,json=bidFactor,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"bid_factor" yaml:"bid_factor"`
	// price indicator only for dutch auctions
	CollateralTokenAuctionPrice github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,7,opt,name=collateral_token_auction_price,json=collateralTokenAuctionPrice,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"collateral_token_auction_price" yaml:"outflow_token_auction_price"`
	CollateralTokenOraclePrice  github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,8,opt,name=collateral_token_oracle_price,json=collateralTokenOraclePrice,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"collateral_token_oracle_price" yaml:"outflow_token_oracle_price"`
	DebtTokenOraclePrice        github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,9,opt,name=debt_token_oracle_price,json=debtTokenOraclePrice,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"debt_token_oracle_price" yaml:"inflow_token_oracle_price"`
	LockedVaultId               uint64                                 `protobuf:"varint,10,opt,name=locked_vault_id,json=lockedVaultId,proto3" json:"locked_vault_id,omitempty" yaml:"locked_vault_id"`
	StartTime                   time.Time                              `protobuf:"bytes,11,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time" yaml:"start_time"`
	EndTime                     time.Time                              `protobuf:"bytes,12,opt,name=end_time,json=endTime,proto3,stdtime" json:"end_time" yaml:"end_time"`
	AppId                       uint64                                 `protobuf:"varint,13,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty" yaml:"app_id"`
	AuctionType                 bool                                   `protobuf:"varint,14,opt,name=auction_type,json=auctionType,proto3" json:"auction_type,omitempty" yaml:"auction_type"`
	CollateralAssetId           uint64                                 `protobuf:"varint,15,opt,name=collateral_asset_id,json=collateralAssetId,proto3" json:"collateral_asset_id,omitempty" yaml:"collateral_asset_id"`
	DebtAssetId                 uint64                                 `protobuf:"varint,16,opt,name=debt_asset_id,json=debtAssetId,proto3" json:"debt_asset_id,omitempty" yaml:"debt_asset_id"`
}

func (m *Auctions) Reset()         { *m = Auctions{} }
func (m *Auctions) String() string { return proto.CompactTextString(m) }
func (*Auctions) ProtoMessage()    {}
func (*Auctions) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ee47f5a405fa8ba, []int{0}
}
func (m *Auctions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Auctions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Auctions.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Auctions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auctions.Merge(m, src)
}
func (m *Auctions) XXX_Size() int {
	return m.Size()
}
func (m *Auctions) XXX_DiscardUnknown() {
	xxx_messageInfo_Auctions.DiscardUnknown(m)
}

var xxx_messageInfo_Auctions proto.InternalMessageInfo

func (m *Auctions) GetAuctionId() uint64 {
	if m != nil {
		return m.AuctionId
	}
	return 0
}

func (m *Auctions) GetCollateralToken() github_com_cosmos_cosmos_sdk_types.Coin {
	if m != nil {
		return m.CollateralToken
	}
	return github_com_cosmos_cosmos_sdk_types.Coin{}
}

func (m *Auctions) GetDebtToken() github_com_cosmos_cosmos_sdk_types.Coin {
	if m != nil {
		return m.DebtToken
	}
	return github_com_cosmos_cosmos_sdk_types.Coin{}
}

func (m *Auctions) GetActiveBiddingId() uint64 {
	if m != nil {
		return m.ActiveBiddingId
	}
	return 0
}

func (m *Auctions) GetBiddingIds() []*BidOwnerMapping {
	if m != nil {
		return m.BiddingIds
	}
	return nil
}

func (m *Auctions) GetLockedVaultId() uint64 {
	if m != nil {
		return m.LockedVaultId
	}
	return 0
}

func (m *Auctions) GetStartTime() time.Time {
	if m != nil {
		return m.StartTime
	}
	return time.Time{}
}

func (m *Auctions) GetEndTime() time.Time {
	if m != nil {
		return m.EndTime
	}
	return time.Time{}
}

func (m *Auctions) GetAppId() uint64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *Auctions) GetAuctionType() bool {
	if m != nil {
		return m.AuctionType
	}
	return false
}

func (m *Auctions) GetCollateralAssetId() uint64 {
	if m != nil {
		return m.CollateralAssetId
	}
	return 0
}

func (m *Auctions) GetDebtAssetId() uint64 {
	if m != nil {
		return m.DebtAssetId
	}
	return 0
}

type BidOwnerMapping struct {
	BidId    uint64 `protobuf:"varint,1,opt,name=bid_id,json=bidId,proto3" json:"bid_id,omitempty"`
	BidOwner string `protobuf:"bytes,2,opt,name=bid_owner,json=bidOwner,proto3" json:"bid_owner,omitempty"`
}

func (m *BidOwnerMapping) Reset()         { *m = BidOwnerMapping{} }
func (m *BidOwnerMapping) String() string { return proto.CompactTextString(m) }
func (*BidOwnerMapping) ProtoMessage()    {}
func (*BidOwnerMapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ee47f5a405fa8ba, []int{1}
}
func (m *BidOwnerMapping) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BidOwnerMapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BidOwnerMapping.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BidOwnerMapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BidOwnerMapping.Merge(m, src)
}
func (m *BidOwnerMapping) XXX_Size() int {
	return m.Size()
}
func (m *BidOwnerMapping) XXX_DiscardUnknown() {
	xxx_messageInfo_BidOwnerMapping.DiscardUnknown(m)
}

var xxx_messageInfo_BidOwnerMapping proto.InternalMessageInfo

func (m *BidOwnerMapping) GetBidId() uint64 {
	if m != nil {
		return m.BidId
	}
	return 0
}

func (m *BidOwnerMapping) GetBidOwner() string {
	if m != nil {
		return m.BidOwner
	}
	return ""
}

func init() {
	proto.RegisterType((*Auctions)(nil), "comdex.auctionsV2.v1beta1.Auctions")
	proto.RegisterType((*BidOwnerMapping)(nil), "comdex.auctionsV2.v1beta1.bidOwnerMapping")
}

func init() {
	proto.RegisterFile("comdex/auctionsV2/v1beta1/auction.proto", fileDescriptor_8ee47f5a405fa8ba)
}

var fileDescriptor_8ee47f5a405fa8ba = []byte{
	// 852 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x4f, 0x8f, 0xdb, 0x44,
	0x14, 0x5f, 0xd3, 0xee, 0x36, 0x99, 0xec, 0x92, 0xae, 0xbb, 0x6d, 0xdd, 0x2c, 0xb5, 0xd3, 0x39,
	0xb4, 0x11, 0x52, 0x6d, 0x75, 0xe9, 0x09, 0x71, 0xa9, 0x0b, 0x88, 0x20, 0xd1, 0xa2, 0x21, 0xaa,
	0x10, 0x17, 0x6b, 0xec, 0x99, 0x84, 0xd1, 0x3a, 0x1e, 0xcb, 0x9e, 0x6c, 0xd9, 0x8f, 0xc0, 0x05,
	0xed, 0x09, 0x89, 0x0f, 0xc1, 0xf7, 0xe8, 0xb1, 0x47, 0xc4, 0xc1, 0xa0, 0xdd, 0x6f, 0xe0, 0x23,
	0x27, 0x34, 0x7f, 0xbc, 0x4e, 0xd2, 0xa2, 0x25, 0xa7, 0x64, 0xde, 0xfc, 0xde, 0xef, 0xfd, 0x66,
	0xfc, 0x7b, 0x6f, 0xc0, 0xa3, 0x84, 0xcf, 0x09, 0xfd, 0x29, 0xc0, 0x8b, 0x44, 0x30, 0x9e, 0x95,
	0xaf, 0x8e, 0x82, 0x93, 0x27, 0x31, 0x15, 0xf8, 0x49, 0x13, 0xf2, 0xf3, 0x82, 0x0b, 0x6e, 0xdf,
	0xd3, 0x40, 0xbf, 0x05, 0xfa, 0x06, 0x38, 0x38, 0x98, 0xf1, 0x19, 0x57, 0xa8, 0x40, 0xfe, 0xd3,
	0x09, 0x03, 0x6f, 0xc6, 0xf9, 0x2c, 0xa5, 0x81, 0x5a, 0xc5, 0x8b, 0x69, 0x20, 0xd8, 0x9c, 0x96,
	0x02, 0xcf, 0x73, 0x03, 0x70, 0x13, 0x5e, 0xce, 0x79, 0x19, 0xc4, 0xb8, 0xa4, 0x97, 0x45, 0x13,
	0xce, 0x4c, 0x45, 0xf8, 0xfb, 0x2e, 0xe8, 0x3c, 0x33, 0xd5, 0xec, 0xa7, 0x00, 0x98, 0xca, 0x11,
	0x23, 0x8e, 0x35, 0xb4, 0x46, 0xd7, 0xc3, 0xdb, 0x75, 0xe5, 0xed, 0x9f, 0xe2, 0x79, 0xfa, 0x29,
	0x6c, 0xf7, 0x20, 0xea, 0x9a, 0xc5, 0x98, 0xd8, 0x67, 0x16, 0xb8, 0x99, 0xf0, 0x34, 0xc5, 0x82,
	0x16, 0x38, 0x8d, 0x04, 0x3f, 0xa6, 0x99, 0xf3, 0xc1, 0xd0, 0x1a, 0xf5, 0x8e, 0xee, 0xf9, 0xba,
	0xbc, 0x2f, 0xcb, 0x37, 0x47, 0xf1, 0x9f, 0x73, 0x96, 0x85, 0x5f, 0xbf, 0xa9, 0xbc, 0xad, 0xba,
	0xf2, 0xee, 0x6a, 0xee, 0x75, 0x02, 0xf8, 0x4f, 0xe5, 0x3d, 0x9a, 0x31, 0xf1, 0xe3, 0x22, 0xf6,
	0x13, 0x3e, 0x0f, 0xcc, 0x31, 0xf4, 0xcf, 0xe3, 0x92, 0x1c, 0x07, 0xe2, 0x34, 0xa7, 0xa5, 0xe2,
	0x42, 0xfd, 0x36, 0x7b, 0x22, 0x93, 0xed, 0x5f, 0x2c, 0x00, 0x08, 0x8d, 0x85, 0x11, 0x73, 0xed,
	0x2a, 0x31, 0x13, 0x23, 0xe6, 0x81, 0x16, 0xc3, 0xb2, 0x69, 0xca, 0x5f, 0xeb, 0xe4, 0x48, 0xe0,
	0x62, 0x46, 0x45, 0x84, 0xe7, 0x7c, 0x91, 0x89, 0x8d, 0x64, 0x75, 0xa5, 0x04, 0x2d, 0xe8, 0x2b,
	0xb0, 0x8f, 0x13, 0xc1, 0x4e, 0x68, 0x14, 0x33, 0x42, 0x58, 0x36, 0x93, 0x17, 0x7c, 0x5d, 0x5d,
	0xf0, 0x47, 0x75, 0xe5, 0x39, 0xe6, 0x82, 0xd7, 0x21, 0x10, 0xf5, 0x75, 0x2c, 0xd4, 0xa1, 0x31,
	0xb1, 0x13, 0xd0, 0x6b, 0xf7, 0x4b, 0x67, 0x7b, 0x78, 0x6d, 0xd4, 0x3b, 0xfa, 0xd8, 0xff, 0x4f,
	0xe3, 0xf8, 0x31, 0x23, 0x2f, 0x5f, 0x67, 0xb4, 0xf8, 0x06, 0xe7, 0x39, 0xcb, 0x66, 0xe1, 0x9d,
	0xba, 0xf2, 0x6c, 0x5d, 0x6f, 0x89, 0x08, 0x22, 0x10, 0x37, 0x35, 0x4a, 0x3b, 0x06, 0x72, 0x15,
	0x4d, 0x71, 0x22, 0x78, 0xe1, 0xec, 0x0c, 0xad, 0x51, 0x37, 0x7c, 0x2e, 0xef, 0xe8, 0xcf, 0xca,
	0x7b, 0xf8, 0x3f, 0x8e, 0xff, 0x39, 0x4d, 0x5a, 0xdb, 0xb4, 0x4c, 0x10, 0x75, 0x63, 0x46, 0xbe,
	0x54, 0xff, 0xed, 0xdf, 0x2c, 0xe0, 0xae, 0x7f, 0xf5, 0xa8, 0xb1, 0x58, 0x5e, 0xb0, 0x84, 0x3a,
	0x37, 0x54, 0xe1, 0xc9, 0xc6, 0x85, 0xa1, 0x2e, 0xcc, 0x17, 0x62, 0xe9, 0x3b, 0xae, 0x50, 0x43,
	0x74, 0xb8, 0xe6, 0x19, 0xd3, 0x04, 0xdf, 0xca, 0x5d, 0xfb, 0x57, 0x0b, 0xdc, 0x7f, 0x47, 0x1b,
	0x2f, 0x70, 0x92, 0x52, 0x23, 0xad, 0xa3, 0xa4, 0x7d, 0xb7, 0xb1, 0xb4, 0x07, 0xef, 0x93, 0xb6,
	0xcc, 0x0c, 0xd1, 0x60, 0x4d, 0xd9, 0x4b, 0xb5, 0xab, 0x85, 0xfd, 0x6c, 0x81, 0xbb, 0xad, 0xb1,
	0x57, 0x25, 0x75, 0x95, 0x24, 0xb4, 0xb1, 0xa4, 0xe1, 0x7b, 0x4c, 0xbf, 0xaa, 0xe8, 0xe0, 0xd2,
	0xc8, 0xcb, 0x5a, 0x42, 0xd0, 0x4f, 0x79, 0x72, 0x4c, 0x49, 0x74, 0x82, 0x17, 0xa9, 0x90, 0x8e,
	0x06, 0xca, 0xd1, 0x83, 0xba, 0xf2, 0xee, 0x68, 0xd2, 0x35, 0x00, 0x44, 0x7b, 0x3a, 0xf2, 0x4a,
	0x06, 0xc6, 0xc4, 0xfe, 0x1e, 0x80, 0x52, 0xe0, 0x42, 0x44, 0x72, 0x6e, 0x39, 0x3d, 0xd5, 0xa7,
	0x03, 0x5f, 0x0f, 0x35, 0xbf, 0x19, 0x6a, 0xfe, 0xa4, 0x19, 0x6a, 0xe1, 0x7d, 0xd3, 0xa8, 0xc6,
	0x5a, 0x6d, 0x2e, 0x3c, 0xfb, 0xcb, 0xb3, 0x50, 0x57, 0x05, 0x24, 0xdc, 0x46, 0xa0, 0x43, 0x33,
	0xa2, 0x79, 0x77, 0xaf, 0xe4, 0x3d, 0x34, 0xbc, 0x7d, 0xcd, 0xdb, 0x64, 0x6a, 0xd6, 0x1b, 0x34,
	0x23, 0x8a, 0x73, 0x04, 0x76, 0x70, 0x9e, 0xcb, 0x83, 0xee, 0xa9, 0x83, 0xee, 0xd7, 0x95, 0xb7,
	0x67, 0x5a, 0x57, 0xc5, 0x21, 0xda, 0xc6, 0x79, 0x3e, 0x26, 0xf6, 0x18, 0xec, 0x36, 0x7e, 0x93,
	0x57, 0xed, 0x7c, 0x38, 0xb4, 0x46, 0x9d, 0xf0, 0xe1, 0x79, 0xe5, 0xf5, 0x8c, 0xd1, 0x26, 0xa7,
	0x39, 0xad, 0x2b, 0xef, 0xd6, 0xea, 0x68, 0x95, 0x60, 0x88, 0x7a, 0xb8, 0xc5, 0xd8, 0x2f, 0xc0,
	0xad, 0x25, 0x2b, 0xe2, 0xb2, 0xa4, 0xea, 0xaa, 0xfb, 0x4a, 0x81, 0x5b, 0x57, 0xde, 0xe0, 0x9d,
	0x09, 0xda, 0x80, 0x20, 0xda, 0x6f, 0xa3, 0xcf, 0x64, 0x70, 0x4c, 0xec, 0xcf, 0xc0, 0x9e, 0x72,
	0xd0, 0x25, 0xd3, 0x4d, 0xc5, 0xe4, 0xd4, 0x95, 0x77, 0xa0, 0x99, 0x56, 0xb6, 0x21, 0xea, 0xc9,
	0xb5, 0xc9, 0x86, 0x5f, 0x80, 0xfe, 0xda, 0x40, 0xb1, 0x6f, 0x83, 0x1d, 0xd9, 0xe2, 0xcd, 0x8b,
	0x81, 0xb6, 0x63, 0x46, 0xc6, 0xc4, 0x3e, 0x04, 0xb2, 0xd9, 0x23, 0x2e, 0xa1, 0xea, 0x39, 0xe8,
	0xa2, 0x4e, 0x93, 0x1a, 0xbe, 0x78, 0x73, 0xee, 0x5a, 0x6f, 0xcf, 0x5d, 0xeb, 0xef, 0x73, 0xd7,
	0x3a, 0xbb, 0x70, 0xb7, 0xde, 0x5e, 0xb8, 0x5b, 0x7f, 0x5c, 0xb8, 0x5b, 0x3f, 0x3c, 0x5d, 0xf1,
	0xad, 0x1c, 0x6a, 0x8f, 0xf9, 0x74, 0xca, 0x12, 0x86, 0x53, 0xb3, 0x0e, 0x56, 0x1e, 0x52, 0xe5,
	0xe4, 0x78, 0x47, 0x7d, 0xd3, 0x4f, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x43, 0x35, 0x4d,
	0x6a, 0x07, 0x00, 0x00,
}

func (m *Auctions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Auctions) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Auctions) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DebtAssetId != 0 {
		i = encodeVarintAuction(dAtA, i, uint64(m.DebtAssetId))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.CollateralAssetId != 0 {
		i = encodeVarintAuction(dAtA, i, uint64(m.CollateralAssetId))
		i--
		dAtA[i] = 0x78
	}
	if m.AuctionType {
		i--
		if m.AuctionType {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x70
	}
	if m.AppId != 0 {
		i = encodeVarintAuction(dAtA, i, uint64(m.AppId))
		i--
		dAtA[i] = 0x68
	}
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.EndTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.EndTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintAuction(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x62
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintAuction(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x5a
	if m.LockedVaultId != 0 {
		i = encodeVarintAuction(dAtA, i, uint64(m.LockedVaultId))
		i--
		dAtA[i] = 0x50
	}
	{
		size := m.DebtTokenOraclePrice.Size()
		i -= size
		if _, err := m.DebtTokenOraclePrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintAuction(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	{
		size := m.CollateralTokenOraclePrice.Size()
		i -= size
		if _, err := m.CollateralTokenOraclePrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintAuction(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.CollateralTokenAuctionPrice.Size()
		i -= size
		if _, err := m.CollateralTokenAuctionPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintAuction(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.BidFactor.Size()
		i -= size
		if _, err := m.BidFactor.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintAuction(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.BiddingIds) > 0 {
		for iNdEx := len(m.BiddingIds) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BiddingIds[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAuction(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.ActiveBiddingId != 0 {
		i = encodeVarintAuction(dAtA, i, uint64(m.ActiveBiddingId))
		i--
		dAtA[i] = 0x20
	}
	{
		size, err := m.DebtToken.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintAuction(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.CollateralToken.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintAuction(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.AuctionId != 0 {
		i = encodeVarintAuction(dAtA, i, uint64(m.AuctionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BidOwnerMapping) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BidOwnerMapping) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BidOwnerMapping) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BidOwner) > 0 {
		i -= len(m.BidOwner)
		copy(dAtA[i:], m.BidOwner)
		i = encodeVarintAuction(dAtA, i, uint64(len(m.BidOwner)))
		i--
		dAtA[i] = 0x12
	}
	if m.BidId != 0 {
		i = encodeVarintAuction(dAtA, i, uint64(m.BidId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintAuction(dAtA []byte, offset int, v uint64) int {
	offset -= sovAuction(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Auctions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AuctionId != 0 {
		n += 1 + sovAuction(uint64(m.AuctionId))
	}
	l = m.CollateralToken.Size()
	n += 1 + l + sovAuction(uint64(l))
	l = m.DebtToken.Size()
	n += 1 + l + sovAuction(uint64(l))
	if m.ActiveBiddingId != 0 {
		n += 1 + sovAuction(uint64(m.ActiveBiddingId))
	}
	if len(m.BiddingIds) > 0 {
		for _, e := range m.BiddingIds {
			l = e.Size()
			n += 1 + l + sovAuction(uint64(l))
		}
	}
	l = m.BidFactor.Size()
	n += 1 + l + sovAuction(uint64(l))
	l = m.CollateralTokenAuctionPrice.Size()
	n += 1 + l + sovAuction(uint64(l))
	l = m.CollateralTokenOraclePrice.Size()
	n += 1 + l + sovAuction(uint64(l))
	l = m.DebtTokenOraclePrice.Size()
	n += 1 + l + sovAuction(uint64(l))
	if m.LockedVaultId != 0 {
		n += 1 + sovAuction(uint64(m.LockedVaultId))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovAuction(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.EndTime)
	n += 1 + l + sovAuction(uint64(l))
	if m.AppId != 0 {
		n += 1 + sovAuction(uint64(m.AppId))
	}
	if m.AuctionType {
		n += 2
	}
	if m.CollateralAssetId != 0 {
		n += 1 + sovAuction(uint64(m.CollateralAssetId))
	}
	if m.DebtAssetId != 0 {
		n += 2 + sovAuction(uint64(m.DebtAssetId))
	}
	return n
}

func (m *BidOwnerMapping) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BidId != 0 {
		n += 1 + sovAuction(uint64(m.BidId))
	}
	l = len(m.BidOwner)
	if l > 0 {
		n += 1 + l + sovAuction(uint64(l))
	}
	return n
}

func sovAuction(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAuction(x uint64) (n int) {
	return sovAuction(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Auctions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Auctions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Auctions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionId", wireType)
			}
			m.AuctionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuctionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralToken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuction
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CollateralToken.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DebtToken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuction
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DebtToken.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveBiddingId", wireType)
			}
			m.ActiveBiddingId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActiveBiddingId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BiddingIds", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuction
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BiddingIds = append(m.BiddingIds, &BidOwnerMapping{})
			if err := m.BiddingIds[len(m.BiddingIds)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BidFactor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BidFactor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralTokenAuctionPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CollateralTokenAuctionPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralTokenOraclePrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CollateralTokenOraclePrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DebtTokenOraclePrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DebtTokenOraclePrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockedVaultId", wireType)
			}
			m.LockedVaultId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LockedVaultId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuction
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuction
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.EndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			m.AppId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionType", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AuctionType = bool(v != 0)
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralAssetId", wireType)
			}
			m.CollateralAssetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CollateralAssetId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DebtAssetId", wireType)
			}
			m.DebtAssetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DebtAssetId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAuction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BidOwnerMapping) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: bidOwnerMapping: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: bidOwnerMapping: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BidId", wireType)
			}
			m.BidId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BidId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BidOwner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BidOwner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAuction(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAuction
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAuction
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAuction
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAuction
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAuction        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAuction          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAuction = fmt.Errorf("proto: unexpected end of group")
)
