package types

// Event types for the liquidity module.
const (
	EventTypeCreatePair       = "create_pair"
	EventTypeCreatePool       = "create_pool"
	EventTypeDeposit          = "deposit"
	EventTypeWithdraw         = "withdraw"
	EventTypeLimitOrder       = "limit_order"
	EventTypeMarketOrder      = "market_order"
	EventTypeCancelOrder      = "cancel_order"
	EventTypeCancelAllOrders  = "cancel_all_orders"
	EventTypeDepositResult    = "deposit_result"
	EventTypeWithdrawalResult = "withdrawal_result"
	EventTypeOrderResult      = "order_result"

	AttributeKeyCreator                 = "creator"
	AttributeKeyDepositor               = "depositor"
	AttributeKeyWithdrawer              = "withdrawer"
	AttributeKeyOrderer                 = "orderer"
	AttributeKeyBaseCoinDenom           = "base_coin_denom"
	AttributeKeyQuoteCoinDenom          = "quote_coin_denom"
	AttributeKeyDepositCoins            = "deposit_coins"
	AttributeKeyAcceptedCoins           = "accepted_coins"
	AttributeKeyMintedPoolCoin          = "minted_pool_coin"
	AttributeKeyPoolCoin                = "pool_coin"
	AttributeKeyWithdrawnCoins          = "withdrawn_coins"
	AttributeKeyRefundedCoins           = "refunded_coins"
	AttributeKeyReserveAddress          = "reserve_address"
	AttributeKeySwapFeeCollectorAddress = "swap_fee_collector_address"
	AttributeKeyEscrowAddress           = "escrow_address"
	AttributeKeyRequestID               = "request_id"
	AttributeKeyPoolID                  = "pool_id"
	AttributeKeyPairID                  = "pair_id"
	AttributeKeyBatchID                 = "batch_id"
	AttributeKeyOrderID                 = "order_id"
	AttributeKeyOrderDirection          = "order_direction"
	AttributeKeyOfferCoin               = "offer_coin"
	AttributeKeyDemandCoinDenom         = "demand_coin_denom"
	AttributeKeyPrice                   = "price"
	AttributeKeyAmount                  = "amount"
	AttributeKeyExpireAt                = "expire_at"
	AttributeKeyRemainingOfferCoin      = "remaining_offer_coin"
	AttributeKeyReceivedCoin            = "received_coin"
	AttributeKeyPairIds                 = "pair_ids"
	AttributeKeyCanceledOrderIds        = "canceled_order_ids"
	AttributeKeyStatus                  = "status"
)
