package types

import (
	errorsmod "cosmossdk.io/errors"
)

var (
	ErrorInvalidAmount                    = errorsmod.Register(ModuleName, 1301, "invalid amount")
	ErrorInvalidAmountIn                  = errorsmod.Register(ModuleName, 1302, "invalid amount_in")
	ErrorInvalidAmountOut                 = errorsmod.Register(ModuleName, 1303, "invalid amount_out")
	ErrorInvalidFrom                      = errorsmod.Register(ModuleName, 1304, "invalid from")
	ErrorInvalidID                        = errorsmod.Register(ModuleName, 1305, "invalid id")
	ErrorExtendedPairVaultDoesNotExists   = errorsmod.Register(ModuleName, 1306, "Extended pair vault does not exists for the given id")
	ErrorAppMappingDoesNotExist           = errorsmod.Register(ModuleName, 1307, "App Mapping Id does not exists")
	ErrorAppMappingIDMismatch             = errorsmod.Register(ModuleName, 1308, "App Mapping Id mismatch, use the correct App Mapping ID in request")
	ErrorVaultCreationInactive            = errorsmod.Register(ModuleName, 1309, "Vault Creation Inactive")
	ErrorUserVaultAlreadyExists           = errorsmod.Register(ModuleName, 1310, "User vault already exists for the given extended pair vault id ")
	ErrorAmountOutLessThanDebtFloor       = errorsmod.Register(ModuleName, 1311, "Amount Out is less than Debt Floor")
	ErrorAmountOutGreaterThanDebtCeiling  = errorsmod.Register(ModuleName, 1312, "Amount Out is greater than Debt Ceiling")
	ErrorPairDoesNotExist                 = errorsmod.Register(ModuleName, 1313, "Pair does not exists")
	ErrorAssetDoesNotExist                = errorsmod.Register(ModuleName, 1314, "Asset does not exists")
	ErrorPriceDoesNotExist                = errorsmod.Register(ModuleName, 1315, "Price does not exist")
	ErrorInvalidCollateralizationRatio    = errorsmod.Register(ModuleName, 1316, "Invalid collateralization ratio")
	ErrorVaultDoesNotExist                = errorsmod.Register(ModuleName, 1317, "Vault does not exist")
	ErrVaultAccessUnauthorised            = errorsmod.Register(ModuleName, 1318, "Unauthorized user for the tx")
	ErrorInvalidAppMappingData            = errorsmod.Register(ModuleName, 1319, "Invalid App Mapping data sent as compared to data exists in vault")
	ErrorInvalidExtendedPairMappingData   = errorsmod.Register(ModuleName, 1320, "Invalid Extended Pair Vault Mapping data sent as compared to data exists in vault")
	ErrorVaultInactive                    = errorsmod.Register(ModuleName, 1321, "Vault tx Inactive")
	ErrorStableMintVaultAlreadyCreated    = errorsmod.Register(ModuleName, 1322, "Stable Mint with this ExtendedPair Already exists, try deposit for stable mint")
	BurnCoinValueInVaultIsZero            = errorsmod.Register(ModuleName, 1323, "Burn Coin value in vault is zero")
	MintCoinValueInVaultIsZero            = errorsmod.Register(ModuleName, 1324, "Mint Coin value in vault is zero")
	ErrorAppExtendedPairDataDoesNotExists = errorsmod.Register(ModuleName, 1325, "App ExtendedPair Data Does Not Exists")
	ErrorUnknownMsgType                   = errorsmod.Register(ModuleName, 1326, "unknown message type")
	ErrorCannotCreateStableMintVault      = errorsmod.Register(ModuleName, 1327, "Cannot Create Stable Mint Vault, StableMint tx command")
)
