package types

import (
	"github.com/cosmos/cosmos-sdk/types/errors"
)

var (
	ErrorInvalidAmount                    = errors.Register(ModuleName, 1301, "invalid amount")
	ErrorInvalidAmountIn                  = errors.Register(ModuleName, 1302, "invalid amount_in")
	ErrorInvalidAmountOut                 = errors.Register(ModuleName, 1303, "invalid amount_out")
	ErrorInvalidFrom                      = errors.Register(ModuleName, 1304, "invalid from")
	ErrorInvalidID                        = errors.Register(ModuleName, 1305, "invalid id")
	ErrorExtendedPairVaultDoesNotExists   = errors.Register(ModuleName, 1306, "Extended pair vault does not exists for the given id")
	ErrorAppMappingDoesNotExist           = errors.Register(ModuleName, 1307, "App Mapping Id does not exists")
	ErrorAppMappingIDMismatch             = errors.Register(ModuleName, 1308, "App Mapping Id mismatch, use the correct App Mapping ID in request")
	ErrorVaultCreationInactive            = errors.Register(ModuleName, 1309, "Vault Creation Inactive")
	ErrorUserVaultAlreadyExists           = errors.Register(ModuleName, 1310, "User vault already exists for the given extended pair vault id ")
	ErrorAmountOutLessThanDebtFloor       = errors.Register(ModuleName, 1311, "Amount Out is less than Debt Floor")
	ErrorAmountOutGreaterThanDebtCeiling  = errors.Register(ModuleName, 1312, "Amount Out is greater than Debt Ceiling")
	ErrorPairDoesNotExist                 = errors.Register(ModuleName, 1313, "Pair does not exists")
	ErrorAssetDoesNotExist                = errors.Register(ModuleName, 1314, "Asset does not exists")
	ErrorPriceDoesNotExist                = errors.Register(ModuleName, 1315, "Price does not exist")
	ErrorInvalidCollateralizationRatio    = errors.Register(ModuleName, 1316, "Invalid collateralization ratio")
	ErrorVaultDoesNotExist                = errors.Register(ModuleName, 1317, "Vault does not exist")
	ErrVaultAccessUnauthorised            = errors.Register(ModuleName, 1318, "Unauthorized user for the tx")
	ErrorInvalidAppMappingData            = errors.Register(ModuleName, 1319, "Invalid App Mapping data sent as compared to data exists in vault")
	ErrorInvalidExtendedPairMappingData   = errors.Register(ModuleName, 1320, "Invalid Extended Pair Vault Mapping data sent as compared to data exists in vault")
	ErrorVaultInactive                    = errors.Register(ModuleName, 1321, "Vault tx Inactive")
	ErrorStableMintVaultAlreadyCreated    = errors.Register(ModuleName, 1322, "Stable Mint with this ExtendedPair Already exists, try deposit for stable mint")
	BurnCoinValueInVaultIsZero            = errors.Register(ModuleName, 1323, "Burn Coin value in vault is zero")
	MintCoinValueInVaultIsZero            = errors.Register(ModuleName, 1324, "Mint Coin value in vault is zero")
	ErrorAppExtendedPairDataDoesNotExists = errors.Register(ModuleName, 1325, "App ExtendedPair Data Does Not Exists")
	ErrorUnknownMsgType                   = errors.Register(ModuleName, 1326, "unknown message type")
	ErrorCannotCreateStableMintVault      = errors.Register(ModuleName, 1327, "Cannot Create Stable Mint Vault, StableMint tx command")
	ErrorWithdrawStableMintVault          = errors.Register(ModuleName, 1328, "Temporary suspension of withdrawals from the Stable Mint Vault")
)
