package types

// DONTCOVER

import (
	sdkerrors "github.com/cosmos/cosmos-sdk/types/errors"
)

var (
	ErrInvalidAsset                    = sdkerrors.Register(ModuleName, 601, "invalid asset")
	ErrLendingPoolInsufficient         = sdkerrors.Register(ModuleName, 602, "lending pool insufficient")
	ErrInvalidRepayment                = sdkerrors.Register(ModuleName, 603, "invalid repayment")
	ErrNegativeTimeElapsed             = sdkerrors.Register(ModuleName, 604, "negative time elapsed since last interest time")
	ErrorUnknownProposalType           = sdkerrors.Register(ModuleName, 605, "unknown proposal type")
	ErrorAssetDoesNotExist             = sdkerrors.Register(ModuleName, 606, "asset does not exist")
	ErrorPairDoesNotExist              = sdkerrors.Register(ModuleName, 607, "pair does not exist")
	ErrBadOfferCoinAmount              = sdkerrors.Register(ModuleName, 608, "invalid offer coin amount")
	ErrorDuplicateLendPair             = sdkerrors.Register(ModuleName, 609, "Duplicate lend Pair")
	ErrLendNotFound                    = sdkerrors.Register(ModuleName, 610, "Lend Position not found")
	ErrLendAccessUnauthorized          = sdkerrors.Register(ModuleName, 611, "Unauthorized user for the tx")
	ErrorPairNotFound                  = sdkerrors.Register(ModuleName, 612, "Pair Not Found")
	ErrorInvalidCollateralizationRatio = sdkerrors.Register(ModuleName, 613, "Error Invalid Collateralization Ratio")
	ErrorDuplicateBorrow               = sdkerrors.Register(ModuleName, 614, "Duplicate borrow Position")
	ErrBorrowingPoolInsufficient       = sdkerrors.Register(ModuleName, 615, "borrowing pool insufficient")
	ErrBorrowNotFound                  = sdkerrors.Register(ModuleName, 616, "Borrow Position not found")
	ErrBorrowingPositionOpen           = sdkerrors.Register(ModuleName, 617, "borrowing position open")
	ErrAssetStatsNotFound              = sdkerrors.Register(ModuleName, 618, "Asset Stats Not Found")
	ErrorAssetStatsNotFound            = sdkerrors.Register(ModuleName, 619, "Asset Stats Not Found")
	ErrInvalidAssetIDForPool           = sdkerrors.Register(ModuleName, 620, "Asset Id not defined in the pool")
	ErrorAssetRatesParamsNotFound      = sdkerrors.Register(ModuleName, 621, "Asset Rates Params not found")
	ErrPoolNotFound                    = sdkerrors.Register(ModuleName, 622, "Pool Not Found")
	ErrAvailableToBorrowInsufficient   = sdkerrors.Register(ModuleName, 623, "Available To Borrow Insufficient")
	ErrStableBorrowDisabled            = sdkerrors.Register(ModuleName, 624, "Stable Borrow Rate Not Enabled for This Asset")
	ErrBadOfferCoinType                = sdkerrors.Register(ModuleName, 625, "invalid offer coin Type")
	ErrInvalidLengthCPoolName          = sdkerrors.Register(ModuleName, 626, "invalid length found during unmarshaling")
	ErrReserveRatesNotFound            = sdkerrors.Register(ModuleName, 627, "Reserve Rates Not found")
	ErrWithdrawAmountLimitExceeds      = sdkerrors.Register(ModuleName, 628, "Withdraw Amount Limit Exceeded")
	ErrorAppMappingDoesNotExist        = sdkerrors.Register(ModuleName, 629, "App Mapping Id does not exists")
	ErrBridgeAssetQtyInsufficient      = sdkerrors.Register(ModuleName, 630, "Bridge Asset Qty Insufficient")
	ErrAverageBorrowRate               = sdkerrors.Register(ModuleName, 631, "Average Borrow Rate Error")
	ErrInsufficientFunds               = sdkerrors.Register(ModuleName, 632, "Insufficient Funds")
	ErrorAppMappingIDMismatch          = sdkerrors.Register(ModuleName, 633, "App Mapping Id mismatch, use the correct App Mapping ID in request")
	ErrorAssetsCanNotBeSame            = sdkerrors.Register(ModuleName, 634, "asset ID of assetIn and assetOut can not be same")
	ErrorSupplyCapExceeds              = sdkerrors.Register(ModuleName, 635, "Supply cap exceeds")
	ErrorBorrowPosLiquidated           = sdkerrors.Register(ModuleName, 636, "Borrow Position Liquidated")
	ErrorInsufficientCTokensForRewards = sdkerrors.Register(ModuleName, 637, "Insufficient CTokens For Rewards in the cPool")
	ErrorAssetRatesParamsAlreadyExists = sdkerrors.Register(ModuleName, 638, "Asset Rates Params already exists")
	ErrorLBMappingNotFound             = sdkerrors.Register(ModuleName, 639, "Asset LB Mapping Not found")
	ErrInsufficientFundsInPool         = sdkerrors.Register(ModuleName, 640, "Insufficient Funds in Pool")
	ErrBorrowLessThanMinAmount         = sdkerrors.Register(ModuleName, 641, "The Borrow amount requested is less than the min borrow limit of 1$")
)
