package types

// DONTCOVER

import (
	errorsmod "cosmossdk.io/errors"
)

var (
	ErrInvalidAsset                    = errorsmod.Register(ModuleName, 601, "invalid asset")
	ErrLendingPoolInsufficient         = errorsmod.Register(ModuleName, 602, "lending pool insufficient")
	ErrInvalidRepayment                = errorsmod.Register(ModuleName, 603, "invalid repayment")
	ErrNegativeTimeElapsed             = errorsmod.Register(ModuleName, 604, "negative time elapsed since last interest time")
	ErrorUnknownProposalType           = errorsmod.Register(ModuleName, 605, "unknown proposal type")
	ErrorAssetDoesNotExist             = errorsmod.Register(ModuleName, 606, "asset does not exist")
	ErrorPairDoesNotExist              = errorsmod.Register(ModuleName, 607, "pair does not exist")
	ErrBadOfferCoinAmount              = errorsmod.Register(ModuleName, 608, "invalid offer coin amount")
	ErrorDuplicateLendPair             = errorsmod.Register(ModuleName, 609, "Duplicate lend Pair")
	ErrLendNotFound                    = errorsmod.Register(ModuleName, 610, "Lend Position not found")
	ErrLendAccessUnauthorized          = errorsmod.Register(ModuleName, 611, "Unauthorized user for the tx")
	ErrorPairNotFound                  = errorsmod.Register(ModuleName, 612, "Pair Not Found")
	ErrorInvalidCollateralizationRatio = errorsmod.Register(ModuleName, 613, "Error Invalid Collateralization Ratio")
	ErrorDuplicateBorrow               = errorsmod.Register(ModuleName, 614, "Duplicate borrow Position")
	ErrBorrowingPoolInsufficient       = errorsmod.Register(ModuleName, 615, "borrowing pool insufficient")
	ErrBorrowNotFound                  = errorsmod.Register(ModuleName, 616, "Borrow Position not found")
	ErrBorrowingPositionOpen           = errorsmod.Register(ModuleName, 617, "borrowing position open")
	ErrAssetStatsNotFound              = errorsmod.Register(ModuleName, 618, "Asset Stats Not Found")
	ErrorAssetStatsNotFound            = errorsmod.Register(ModuleName, 619, "Asset Stats Not Found")
	ErrInvalidAssetIDForPool           = errorsmod.Register(ModuleName, 620, "Asset Id not defined in the pool")
	ErrorAssetRatesParamsNotFound      = errorsmod.Register(ModuleName, 621, "Asset Rates Params not found")
	ErrPoolNotFound                    = errorsmod.Register(ModuleName, 622, "Pool Not Found")
	ErrAvailableToBorrowInsufficient   = errorsmod.Register(ModuleName, 623, "Available To Borrow Insufficient")
	ErrStableBorrowDisabled            = errorsmod.Register(ModuleName, 624, "Stable Borrow Rate Not Enabled for This Asset")
	ErrBadOfferCoinType                = errorsmod.Register(ModuleName, 625, "invalid offer coin Type")
	ErrInvalidLengthCPoolName          = errorsmod.Register(ModuleName, 626, "invalid length found during unmarshaling")
	ErrReserveRatesNotFound            = errorsmod.Register(ModuleName, 627, "Reserve Rates Not found")
	ErrWithdrawAmountLimitExceeds      = errorsmod.Register(ModuleName, 628, "Withdraw Amount Limit Exceeded")
	ErrorAppMappingDoesNotExist        = errorsmod.Register(ModuleName, 629, "App Mapping Id does not exists")
	ErrBridgeAssetQtyInsufficient      = errorsmod.Register(ModuleName, 630, "Bridge Asset Qty Insufficient")
	ErrAverageBorrowRate               = errorsmod.Register(ModuleName, 631, "Average Borrow Rate Error")
	ErrInsufficientFunds               = errorsmod.Register(ModuleName, 632, "Insufficient Funds")
	ErrorAppMappingIDMismatch          = errorsmod.Register(ModuleName, 633, "App Mapping Id mismatch, use the correct App Mapping ID in request")
	ErrorAssetsCanNotBeSame            = errorsmod.Register(ModuleName, 634, "asset ID of assetIn and assetOut can not be same")
	ErrorSupplyCapExceeds              = errorsmod.Register(ModuleName, 635, "Supply cap exceeds")
	ErrorBorrowPosLiquidated           = errorsmod.Register(ModuleName, 636, "Borrow Position Liquidated")
	ErrorInsufficientCTokensForRewards = errorsmod.Register(ModuleName, 637, "Insufficient CTokens For Rewards in the cPool")
	ErrorAssetRatesParamsAlreadyExists = errorsmod.Register(ModuleName, 638, "Asset Rates Params already exists")
	ErrorLBMappingNotFound             = errorsmod.Register(ModuleName, 639, "Asset LB Mapping Not found")
	ErrInsufficientFundsInPool         = errorsmod.Register(ModuleName, 640, "Insufficient Funds in Pool")
	ErrBorrowLessThanMinAmount         = errorsmod.Register(ModuleName, 641, "The Borrow amount requested is less than the min borrow limit of 1$")
	ErrorEmptyProposalAssets           = errorsmod.Register(ModuleName, 642, "Empty proposal for asset")
	ErrorPoolDepreciated               = errorsmod.Register(ModuleName, 643, "Pool is depreciated, lending and borrowing are restricted, users can repay and withdraw their funds")
	ErrorIsolatedModeActivated         = errorsmod.Register(ModuleName, 644, "Isolated-Mode Activated for the asset, multiple borrow positions are restricted")
)
