// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: comdex/collector/v1beta1/collector.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CollectorData struct {
	CollectedStabilityFee       github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,1,opt,name=collected_stability_fee,json=collectedStabilityFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"collected_stability_fee" yaml:"collected_stability_fee"`
	CollectedClosingFee         github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,2,opt,name=collected_closing_fee,json=collectedClosingFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"collected_closing_fee" yaml:"collected_closing_fee"`
	CollectedOpeningFee         github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=collected_opening_fee,json=collectedOpeningFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"collected_opening_fee" yaml:"collected_opening_fee"`
	LiquidationRewardsCollected github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,5,opt,name=liquidation_rewards_collected,json=liquidationRewardsCollected,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"liquidation_rewards_collected" yaml:"liquidation_rewards_collected"`
}

func (m *CollectorData) Reset()         { *m = CollectorData{} }
func (m *CollectorData) String() string { return proto.CompactTextString(m) }
func (*CollectorData) ProtoMessage()    {}
func (*CollectorData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f18765a8dff2a43b, []int{0}
}
func (m *CollectorData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CollectorData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CollectorData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CollectorData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectorData.Merge(m, src)
}
func (m *CollectorData) XXX_Size() int {
	return m.Size()
}
func (m *CollectorData) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectorData.DiscardUnknown(m)
}

var xxx_messageInfo_CollectorData proto.InternalMessageInfo

type NetFeeCollectedData struct {
	AppId                 uint64                  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty" yaml:"app_id"`
	AssetIdToFeeCollected []AssetIdToFeeCollected `protobuf:"bytes,2,rep,name=assetIdToFeeCollected,proto3" json:"assetIdToFeeCollected" yaml:"asset_id_to_fee_collected"`
}

func (m *NetFeeCollectedData) Reset()         { *m = NetFeeCollectedData{} }
func (m *NetFeeCollectedData) String() string { return proto.CompactTextString(m) }
func (*NetFeeCollectedData) ProtoMessage()    {}
func (*NetFeeCollectedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f18765a8dff2a43b, []int{1}
}
func (m *NetFeeCollectedData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NetFeeCollectedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NetFeeCollectedData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NetFeeCollectedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetFeeCollectedData.Merge(m, src)
}
func (m *NetFeeCollectedData) XXX_Size() int {
	return m.Size()
}
func (m *NetFeeCollectedData) XXX_DiscardUnknown() {
	xxx_messageInfo_NetFeeCollectedData.DiscardUnknown(m)
}

var xxx_messageInfo_NetFeeCollectedData proto.InternalMessageInfo

func (m *NetFeeCollectedData) GetAppId() uint64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *NetFeeCollectedData) GetAssetIdToFeeCollected() []AssetIdToFeeCollected {
	if m != nil {
		return m.AssetIdToFeeCollected
	}
	return nil
}

type AssetIdToFeeCollected struct {
	AssetId          uint64                                 `protobuf:"varint,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty" yaml:"asset_id"`
	NetFeesCollected github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,2,opt,name=net_fees_collected,json=netFeesCollected,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"net_fees_collected" yaml:"net_fees_collected"`
}

func (m *AssetIdToFeeCollected) Reset()         { *m = AssetIdToFeeCollected{} }
func (m *AssetIdToFeeCollected) String() string { return proto.CompactTextString(m) }
func (*AssetIdToFeeCollected) ProtoMessage()    {}
func (*AssetIdToFeeCollected) Descriptor() ([]byte, []int) {
	return fileDescriptor_f18765a8dff2a43b, []int{2}
}
func (m *AssetIdToFeeCollected) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AssetIdToFeeCollected) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AssetIdToFeeCollected.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AssetIdToFeeCollected) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetIdToFeeCollected.Merge(m, src)
}
func (m *AssetIdToFeeCollected) XXX_Size() int {
	return m.Size()
}
func (m *AssetIdToFeeCollected) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetIdToFeeCollected.DiscardUnknown(m)
}

var xxx_messageInfo_AssetIdToFeeCollected proto.InternalMessageInfo

func (m *AssetIdToFeeCollected) GetAssetId() uint64 {
	if m != nil {
		return m.AssetId
	}
	return 0
}

type AppIdToAssetCollectorMapping struct {
	AppId          uint64                    `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty" yaml:"app_id"`
	AssetCollector []AssetIdCollectorMapping `protobuf:"bytes,2,rep,name=asset_collector,json=assetCollector,proto3" json:"asset_collector" yaml:"asset_collector"`
}

func (m *AppIdToAssetCollectorMapping) Reset()         { *m = AppIdToAssetCollectorMapping{} }
func (m *AppIdToAssetCollectorMapping) String() string { return proto.CompactTextString(m) }
func (*AppIdToAssetCollectorMapping) ProtoMessage()    {}
func (*AppIdToAssetCollectorMapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_f18765a8dff2a43b, []int{3}
}
func (m *AppIdToAssetCollectorMapping) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AppIdToAssetCollectorMapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AppIdToAssetCollectorMapping.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AppIdToAssetCollectorMapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppIdToAssetCollectorMapping.Merge(m, src)
}
func (m *AppIdToAssetCollectorMapping) XXX_Size() int {
	return m.Size()
}
func (m *AppIdToAssetCollectorMapping) XXX_DiscardUnknown() {
	xxx_messageInfo_AppIdToAssetCollectorMapping.DiscardUnknown(m)
}

var xxx_messageInfo_AppIdToAssetCollectorMapping proto.InternalMessageInfo

func (m *AppIdToAssetCollectorMapping) GetAppId() uint64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *AppIdToAssetCollectorMapping) GetAssetCollector() []AssetIdCollectorMapping {
	if m != nil {
		return m.AssetCollector
	}
	return nil
}

type AssetIdCollectorMapping struct {
	AssetId   uint64        `protobuf:"varint,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty" yaml:"asset_id"`
	Collector CollectorData `protobuf:"bytes,2,opt,name=collector,proto3" json:"collector" yaml:"collector"`
}

func (m *AssetIdCollectorMapping) Reset()         { *m = AssetIdCollectorMapping{} }
func (m *AssetIdCollectorMapping) String() string { return proto.CompactTextString(m) }
func (*AssetIdCollectorMapping) ProtoMessage()    {}
func (*AssetIdCollectorMapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_f18765a8dff2a43b, []int{4}
}
func (m *AssetIdCollectorMapping) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AssetIdCollectorMapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AssetIdCollectorMapping.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AssetIdCollectorMapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetIdCollectorMapping.Merge(m, src)
}
func (m *AssetIdCollectorMapping) XXX_Size() int {
	return m.Size()
}
func (m *AssetIdCollectorMapping) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetIdCollectorMapping.DiscardUnknown(m)
}

var xxx_messageInfo_AssetIdCollectorMapping proto.InternalMessageInfo

func (m *AssetIdCollectorMapping) GetAssetId() uint64 {
	if m != nil {
		return m.AssetId
	}
	return 0
}

func (m *AssetIdCollectorMapping) GetCollector() CollectorData {
	if m != nil {
		return m.Collector
	}
	return CollectorData{}
}

type CollectorLookupTable struct {
	AppId            uint64                                 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty" yaml:"app_id"`
	CollectorAssetId uint64                                 `protobuf:"varint,2,opt,name=collector_asset_id,json=collectorAssetId,proto3" json:"collector_asset_id,omitempty" yaml:"collector_asset_id"`
	SecondaryAssetId uint64                                 `protobuf:"varint,3,opt,name=secondary_asset_id,json=secondaryAssetId,proto3" json:"secondary_asset_id,omitempty" yaml:"secondary_asset_id"`
	SurplusThreshold uint64                                 `protobuf:"varint,4,opt,name=surplus_threshold,json=surplusThreshold,proto3" json:"surplus_threshold,omitempty" yaml:"surplus_threshold"`
	DebtThreshold    uint64                                 `protobuf:"varint,5,opt,name=debt_threshold,json=debtThreshold,proto3" json:"debt_threshold,omitempty" yaml:"debt_threshold"`
	LockerSavingRate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,6,opt,name=locker_saving_rate,json=lockerSavingRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"locker_saving_rate" yaml:"locker_saving_rate"`
	LotSize          uint64                                 `protobuf:"varint,7,opt,name=lot_size,json=lotSize,proto3" json:"lot_size,omitempty" yaml:"lot_size"`
	BidFactor        github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,8,opt,name=bid_factor,json=bidFactor,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"bid_factor" yaml:"bid_factor"`
}

func (m *CollectorLookupTable) Reset()         { *m = CollectorLookupTable{} }
func (m *CollectorLookupTable) String() string { return proto.CompactTextString(m) }
func (*CollectorLookupTable) ProtoMessage()    {}
func (*CollectorLookupTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_f18765a8dff2a43b, []int{5}
}
func (m *CollectorLookupTable) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CollectorLookupTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CollectorLookupTable.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CollectorLookupTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectorLookupTable.Merge(m, src)
}
func (m *CollectorLookupTable) XXX_Size() int {
	return m.Size()
}
func (m *CollectorLookupTable) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectorLookupTable.DiscardUnknown(m)
}

var xxx_messageInfo_CollectorLookupTable proto.InternalMessageInfo

func (m *CollectorLookupTable) GetAppId() uint64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *CollectorLookupTable) GetCollectorAssetId() uint64 {
	if m != nil {
		return m.CollectorAssetId
	}
	return 0
}

func (m *CollectorLookupTable) GetSecondaryAssetId() uint64 {
	if m != nil {
		return m.SecondaryAssetId
	}
	return 0
}

func (m *CollectorLookupTable) GetSurplusThreshold() uint64 {
	if m != nil {
		return m.SurplusThreshold
	}
	return 0
}

func (m *CollectorLookupTable) GetDebtThreshold() uint64 {
	if m != nil {
		return m.DebtThreshold
	}
	return 0
}

func (m *CollectorLookupTable) GetLotSize() uint64 {
	if m != nil {
		return m.LotSize
	}
	return 0
}

type CollectorLookup struct {
	AppId         uint64                 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty" yaml:"app_id"`
	AssetRateInfo []CollectorLookupTable `protobuf:"bytes,2,rep,name=asset_rate_info,json=assetRateInfo,proto3" json:"asset_rate_info" yaml:"asset_rate_info"`
}

func (m *CollectorLookup) Reset()         { *m = CollectorLookup{} }
func (m *CollectorLookup) String() string { return proto.CompactTextString(m) }
func (*CollectorLookup) ProtoMessage()    {}
func (*CollectorLookup) Descriptor() ([]byte, []int) {
	return fileDescriptor_f18765a8dff2a43b, []int{6}
}
func (m *CollectorLookup) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CollectorLookup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CollectorLookup.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CollectorLookup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectorLookup.Merge(m, src)
}
func (m *CollectorLookup) XXX_Size() int {
	return m.Size()
}
func (m *CollectorLookup) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectorLookup.DiscardUnknown(m)
}

var xxx_messageInfo_CollectorLookup proto.InternalMessageInfo

func (m *CollectorLookup) GetAppId() uint64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *CollectorLookup) GetAssetRateInfo() []CollectorLookupTable {
	if m != nil {
		return m.AssetRateInfo
	}
	return nil
}

type AppToDenomsMapping struct {
	AppId    uint64   `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty" yaml:"app_id"`
	AssetIds []uint64 `protobuf:"varint,2,rep,packed,name=asset_ids,json=assetIds,proto3" json:"asset_ids,omitempty" yaml:"asset_ids"`
}

func (m *AppToDenomsMapping) Reset()         { *m = AppToDenomsMapping{} }
func (m *AppToDenomsMapping) String() string { return proto.CompactTextString(m) }
func (*AppToDenomsMapping) ProtoMessage()    {}
func (*AppToDenomsMapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_f18765a8dff2a43b, []int{7}
}
func (m *AppToDenomsMapping) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AppToDenomsMapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AppToDenomsMapping.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AppToDenomsMapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppToDenomsMapping.Merge(m, src)
}
func (m *AppToDenomsMapping) XXX_Size() int {
	return m.Size()
}
func (m *AppToDenomsMapping) XXX_DiscardUnknown() {
	xxx_messageInfo_AppToDenomsMapping.DiscardUnknown(m)
}

var xxx_messageInfo_AppToDenomsMapping proto.InternalMessageInfo

func (m *AppToDenomsMapping) GetAppId() uint64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *AppToDenomsMapping) GetAssetIds() []uint64 {
	if m != nil {
		return m.AssetIds
	}
	return nil
}

type HistoricalAuction struct {
	AppId          uint64                   `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty" yaml:"app_id"`
	AssetToAuction []*AssetToAuctionMapping `protobuf:"bytes,2,rep,name=asset_to_auction,json=assetToAuction,proto3" json:"asset_to_auction,omitempty" yaml:"asset_to_auction"`
}

func (m *HistoricalAuction) Reset()         { *m = HistoricalAuction{} }
func (m *HistoricalAuction) String() string { return proto.CompactTextString(m) }
func (*HistoricalAuction) ProtoMessage()    {}
func (*HistoricalAuction) Descriptor() ([]byte, []int) {
	return fileDescriptor_f18765a8dff2a43b, []int{8}
}
func (m *HistoricalAuction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HistoricalAuction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HistoricalAuction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HistoricalAuction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoricalAuction.Merge(m, src)
}
func (m *HistoricalAuction) XXX_Size() int {
	return m.Size()
}
func (m *HistoricalAuction) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoricalAuction.DiscardUnknown(m)
}

var xxx_messageInfo_HistoricalAuction proto.InternalMessageInfo

func (m *HistoricalAuction) GetAppId() uint64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *HistoricalAuction) GetAssetToAuction() []*AssetToAuctionMapping {
	if m != nil {
		return m.AssetToAuction
	}
	return nil
}

type AssetToAuctionMapping struct {
	AuctionId   uint64   `protobuf:"varint,1,opt,name=auctionId,proto3" json:"auctionId,omitempty" yaml:"auction_id"`
	AssetDenoms []string `protobuf:"bytes,2,rep,name=asset_denoms,json=assetDenoms,proto3" json:"asset_denoms,omitempty" yaml:"asset_denoms"`
}

func (m *AssetToAuctionMapping) Reset()         { *m = AssetToAuctionMapping{} }
func (m *AssetToAuctionMapping) String() string { return proto.CompactTextString(m) }
func (*AssetToAuctionMapping) ProtoMessage()    {}
func (*AssetToAuctionMapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_f18765a8dff2a43b, []int{9}
}
func (m *AssetToAuctionMapping) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AssetToAuctionMapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AssetToAuctionMapping.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AssetToAuctionMapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetToAuctionMapping.Merge(m, src)
}
func (m *AssetToAuctionMapping) XXX_Size() int {
	return m.Size()
}
func (m *AssetToAuctionMapping) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetToAuctionMapping.DiscardUnknown(m)
}

var xxx_messageInfo_AssetToAuctionMapping proto.InternalMessageInfo

func (m *AssetToAuctionMapping) GetAuctionId() uint64 {
	if m != nil {
		return m.AuctionId
	}
	return 0
}

func (m *AssetToAuctionMapping) GetAssetDenoms() []string {
	if m != nil {
		return m.AssetDenoms
	}
	return nil
}

// key app id -> assets  traverse this one
type CollectorAuctionLookupTable struct {
	AppId                  uint64                        `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty" yaml:"app_id"`
	AssetIdToAuctionLookup []AssetIdToAuctionLookupTable `protobuf:"bytes,2,rep,name=assetIdToAuctionLookup,proto3" json:"assetIdToAuctionLookup" yaml:"asset_id_to_auction_lookup"`
}

func (m *CollectorAuctionLookupTable) Reset()         { *m = CollectorAuctionLookupTable{} }
func (m *CollectorAuctionLookupTable) String() string { return proto.CompactTextString(m) }
func (*CollectorAuctionLookupTable) ProtoMessage()    {}
func (*CollectorAuctionLookupTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_f18765a8dff2a43b, []int{10}
}
func (m *CollectorAuctionLookupTable) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CollectorAuctionLookupTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CollectorAuctionLookupTable.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CollectorAuctionLookupTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectorAuctionLookupTable.Merge(m, src)
}
func (m *CollectorAuctionLookupTable) XXX_Size() int {
	return m.Size()
}
func (m *CollectorAuctionLookupTable) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectorAuctionLookupTable.DiscardUnknown(m)
}

var xxx_messageInfo_CollectorAuctionLookupTable proto.InternalMessageInfo

func (m *CollectorAuctionLookupTable) GetAppId() uint64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *CollectorAuctionLookupTable) GetAssetIdToAuctionLookup() []AssetIdToAuctionLookupTable {
	if m != nil {
		return m.AssetIdToAuctionLookup
	}
	return nil
}

type AssetIdToAuctionLookupTable struct {
	AssetId             uint64 `protobuf:"varint,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty" yaml:"asset_id"`
	IsSurplusAuction    bool   `protobuf:"varint,2,opt,name=is_surplus_auction,json=isSurplusAuction,proto3" json:"is_surplus_auction,omitempty" yaml:"is_surplus_auction"`
	IsDebtAuction       bool   `protobuf:"varint,3,opt,name=is_debt_auction,json=isDebtAuction,proto3" json:"is_debt_auction,omitempty" yaml:"is_debt_auction"`
	IsAuctionActive     bool   `protobuf:"varint,4,opt,name=is_auction_active,json=isAuctionActive,proto3" json:"is_auction_active,omitempty" yaml:"is_auction_active"`
	AssetOutOraclePrice bool   `protobuf:"varint,15,opt,name=asset_out_oracle_price,json=assetOutOraclePrice,proto3" json:"asset_out_oracle_price,omitempty" yaml:"asset_out_oracle_price"`
	AssetOutPrice       uint64 `protobuf:"varint,16,opt,name=asset_out_price,json=assetOutPrice,proto3" json:"asset_out_price,omitempty" yaml:"asset_out_price"`
}

func (m *AssetIdToAuctionLookupTable) Reset()         { *m = AssetIdToAuctionLookupTable{} }
func (m *AssetIdToAuctionLookupTable) String() string { return proto.CompactTextString(m) }
func (*AssetIdToAuctionLookupTable) ProtoMessage()    {}
func (*AssetIdToAuctionLookupTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_f18765a8dff2a43b, []int{11}
}
func (m *AssetIdToAuctionLookupTable) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AssetIdToAuctionLookupTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AssetIdToAuctionLookupTable.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AssetIdToAuctionLookupTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetIdToAuctionLookupTable.Merge(m, src)
}
func (m *AssetIdToAuctionLookupTable) XXX_Size() int {
	return m.Size()
}
func (m *AssetIdToAuctionLookupTable) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetIdToAuctionLookupTable.DiscardUnknown(m)
}

var xxx_messageInfo_AssetIdToAuctionLookupTable proto.InternalMessageInfo

func (m *AssetIdToAuctionLookupTable) GetAssetId() uint64 {
	if m != nil {
		return m.AssetId
	}
	return 0
}

func (m *AssetIdToAuctionLookupTable) GetIsSurplusAuction() bool {
	if m != nil {
		return m.IsSurplusAuction
	}
	return false
}

func (m *AssetIdToAuctionLookupTable) GetIsDebtAuction() bool {
	if m != nil {
		return m.IsDebtAuction
	}
	return false
}

func (m *AssetIdToAuctionLookupTable) GetIsAuctionActive() bool {
	if m != nil {
		return m.IsAuctionActive
	}
	return false
}

func (m *AssetIdToAuctionLookupTable) GetAssetOutOraclePrice() bool {
	if m != nil {
		return m.AssetOutOraclePrice
	}
	return false
}

func (m *AssetIdToAuctionLookupTable) GetAssetOutPrice() uint64 {
	if m != nil {
		return m.AssetOutPrice
	}
	return 0
}

func init() {
	proto.RegisterType((*CollectorData)(nil), "comdex.collector.v1beta1.CollectorData")
	proto.RegisterType((*NetFeeCollectedData)(nil), "comdex.collector.v1beta1.NetFeeCollectedData")
	proto.RegisterType((*AssetIdToFeeCollected)(nil), "comdex.collector.v1beta1.AssetIdToFeeCollected")
	proto.RegisterType((*AppIdToAssetCollectorMapping)(nil), "comdex.collector.v1beta1.AppIdToAssetCollectorMapping")
	proto.RegisterType((*AssetIdCollectorMapping)(nil), "comdex.collector.v1beta1.AssetIdCollectorMapping")
	proto.RegisterType((*CollectorLookupTable)(nil), "comdex.collector.v1beta1.CollectorLookupTable")
	proto.RegisterType((*CollectorLookup)(nil), "comdex.collector.v1beta1.CollectorLookup")
	proto.RegisterType((*AppToDenomsMapping)(nil), "comdex.collector.v1beta1.AppToDenomsMapping")
	proto.RegisterType((*HistoricalAuction)(nil), "comdex.collector.v1beta1.HistoricalAuction")
	proto.RegisterType((*AssetToAuctionMapping)(nil), "comdex.collector.v1beta1.AssetToAuctionMapping")
	proto.RegisterType((*CollectorAuctionLookupTable)(nil), "comdex.collector.v1beta1.CollectorAuctionLookupTable")
	proto.RegisterType((*AssetIdToAuctionLookupTable)(nil), "comdex.collector.v1beta1.AssetIdToAuctionLookupTable")
}

func init() {
	proto.RegisterFile("comdex/collector/v1beta1/collector.proto", fileDescriptor_f18765a8dff2a43b)
}

var fileDescriptor_f18765a8dff2a43b = []byte{
	// 1166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x4d, 0x4f, 0x1b, 0x47,
	0x18, 0x66, 0xc3, 0xa7, 0x87, 0x12, 0x9b, 0x05, 0x82, 0xc3, 0x87, 0x97, 0x8c, 0xaa, 0xd6, 0x3d,
	0xc4, 0x16, 0x41, 0xbd, 0xe4, 0x54, 0x0c, 0x42, 0xb1, 0x68, 0x42, 0x34, 0x58, 0x39, 0xf4, 0x32,
	0x1a, 0xef, 0x0e, 0x30, 0x62, 0xf1, 0x6c, 0x76, 0xc6, 0xb4, 0xe6, 0xd8, 0x53, 0x6e, 0xed, 0xb1,
	0xea, 0x4f, 0xe8, 0xb5, 0xea, 0x0f, 0x68, 0x95, 0x43, 0x8e, 0xe9, 0xad, 0xea, 0x61, 0x55, 0xc1,
	0x3f, 0xf0, 0xa1, 0xe7, 0x6a, 0x67, 0xf6, 0xcb, 0x36, 0x4e, 0xd9, 0xaa, 0x27, 0xec, 0xe7, 0x7d,
	0xe7, 0x79, 0x9f, 0xf7, 0x63, 0xde, 0xc1, 0xa0, 0x6a, 0xf3, 0x0b, 0x87, 0x7e, 0x53, 0xb7, 0xb9,
	0xeb, 0x52, 0x5b, 0x72, 0xbf, 0x7e, 0xb9, 0xdd, 0xa6, 0x92, 0x6c, 0xa7, 0x48, 0xcd, 0xf3, 0xb9,
	0xe4, 0x66, 0x59, 0x7b, 0xd6, 0x52, 0x3c, 0xf2, 0x5c, 0x5b, 0x3e, 0xe5, 0xa7, 0x5c, 0x39, 0xd5,
	0xc3, 0x4f, 0xda, 0x1f, 0xfe, 0x3a, 0x05, 0x16, 0xf6, 0x62, 0xdf, 0x7d, 0x22, 0x89, 0xf9, 0xc6,
	0x00, 0xab, 0xd1, 0x69, 0xea, 0x60, 0x21, 0x49, 0x9b, 0xb9, 0x4c, 0xf6, 0xf0, 0x09, 0xa5, 0x65,
	0x63, 0xcb, 0xa8, 0x16, 0x1a, 0x2f, 0xdf, 0x05, 0xd6, 0xc4, 0x9f, 0x81, 0xf5, 0xc9, 0x29, 0x93,
	0x67, 0xdd, 0x76, 0xcd, 0xe6, 0x17, 0x75, 0x9b, 0x8b, 0x0b, 0x2e, 0xa2, 0x3f, 0x8f, 0x85, 0x73,
	0x5e, 0x97, 0x3d, 0x8f, 0x8a, 0x5a, 0xb3, 0x23, 0xfb, 0x81, 0x55, 0xe9, 0x91, 0x0b, 0xf7, 0x29,
	0x1c, 0x43, 0x0b, 0xd1, 0x4a, 0x62, 0x39, 0x8e, 0x0d, 0x07, 0x94, 0x9a, 0xdf, 0x1a, 0x20, 0xb5,
	0x60, 0xdb, 0xe5, 0x82, 0x75, 0x4e, 0x95, 0x90, 0x7b, 0x4a, 0xc8, 0x8b, 0xdc, 0x42, 0x36, 0x86,
	0x85, 0x64, 0x48, 0x21, 0x5a, 0x4a, 0xf0, 0x3d, 0x0d, 0x8f, 0x8a, 0xe0, 0x1e, 0xed, 0xc4, 0x22,
	0x26, 0xff, 0x2f, 0x11, 0x19, 0xd2, 0xac, 0x88, 0x23, 0x0d, 0x87, 0x22, 0x7e, 0x34, 0xc0, 0xa6,
	0xcb, 0x5e, 0x77, 0x99, 0x43, 0x24, 0xe3, 0x1d, 0xec, 0xd3, 0xaf, 0x89, 0xef, 0x08, 0x9c, 0xf8,
	0x96, 0xa7, 0x95, 0x98, 0x57, 0xb9, 0xc5, 0x7c, 0xac, 0xc5, 0x7c, 0x90, 0x1c, 0xa2, 0xf5, 0x8c,
	0x1d, 0x69, 0xf3, 0x5e, 0x62, 0xfd, 0xdd, 0x00, 0x4b, 0x2f, 0xa8, 0x3c, 0xa0, 0x34, 0xc1, 0xd4,
	0x24, 0x55, 0xc1, 0x0c, 0xf1, 0x3c, 0xcc, 0x1c, 0x35, 0x37, 0x53, 0x8d, 0xc5, 0x7e, 0x60, 0x2d,
	0xe8, 0x70, 0x1a, 0x87, 0x68, 0x9a, 0x78, 0x5e, 0xd3, 0x31, 0xbf, 0x33, 0xc0, 0x0a, 0x11, 0x82,
	0xca, 0xa6, 0xd3, 0xe2, 0x59, 0x9e, 0xf2, 0xbd, 0xad, 0xc9, 0xea, 0xfc, 0x93, 0x7a, 0x6d, 0xdc,
	0x58, 0xd7, 0x76, 0x6f, 0x3b, 0xd6, 0xa8, 0x86, 0x75, 0xe8, 0x07, 0xd6, 0x56, 0x14, 0x2e, 0x74,
	0xc2, 0xcc, 0xc1, 0x92, 0x87, 0x45, 0xce, 0x66, 0x76, 0x7b, 0x5c, 0xf8, 0x9b, 0x01, 0x56, 0x6e,
	0xa5, 0x36, 0x6b, 0x60, 0x2e, 0xa6, 0x8b, 0xf2, 0x5a, 0xea, 0x07, 0x56, 0x71, 0x30, 0x10, 0x44,
	0xb3, 0x11, 0xaf, 0xd9, 0x03, 0x66, 0x87, 0xca, 0x30, 0x6c, 0xb6, 0x5d, 0x7a, 0x80, 0x0f, 0x73,
	0xb7, 0xeb, 0xa1, 0x8e, 0x33, 0xca, 0x08, 0x51, 0xa9, 0xa3, 0x7a, 0x90, 0x69, 0xcc, 0x5b, 0x03,
	0x6c, 0xec, 0x86, 0x05, 0x6e, 0x71, 0x95, 0x4b, 0x72, 0xd1, 0x9f, 0x13, 0xcf, 0x63, 0x9d, 0xd3,
	0x1c, 0x1d, 0xba, 0x02, 0x45, 0x9d, 0x5b, 0xd2, 0x81, 0xa8, 0x35, 0xdb, 0xff, 0xda, 0x9a, 0xe1,
	0xa8, 0x8d, 0x4a, 0xd4, 0x9c, 0x07, 0xd9, 0x9a, 0x25, 0xc7, 0x21, 0xba, 0x4f, 0x06, 0xc4, 0xc2,
	0x9f, 0x0c, 0xb0, 0x3a, 0x86, 0x2b, 0x77, 0x37, 0x30, 0x28, 0x64, 0x33, 0x30, 0xaa, 0xf3, 0x4f,
	0x3e, 0x1d, 0x9f, 0xc1, 0xc0, 0x66, 0x6c, 0x94, 0x23, 0xdd, 0xa5, 0x81, 0xfb, 0x1b, 0x2a, 0x4e,
	0x39, 0xe1, 0xdf, 0x53, 0x60, 0x39, 0x39, 0xf6, 0x25, 0xe7, 0xe7, 0x5d, 0xaf, 0x45, 0xda, 0x2e,
	0xcd, 0x51, 0xeb, 0x43, 0x60, 0x26, 0x7c, 0x38, 0xc9, 0xee, 0x9e, 0x3a, 0xb5, 0x99, 0xce, 0xc0,
	0xa8, 0x0f, 0x44, 0xa5, 0x04, 0x8c, 0x0a, 0x16, 0x92, 0x09, 0x6a, 0xf3, 0x8e, 0x43, 0xfc, 0x5e,
	0x4a, 0x36, 0x39, 0x4c, 0x36, 0xea, 0x03, 0x51, 0x29, 0x01, 0x63, 0xb2, 0x26, 0x58, 0x14, 0x5d,
	0xdf, 0x73, 0xbb, 0x02, 0xcb, 0x33, 0x9f, 0x8a, 0x33, 0xee, 0x3a, 0xe5, 0x29, 0xc5, 0xb5, 0xd1,
	0x0f, 0xac, 0x72, 0xc4, 0x35, 0xec, 0x12, 0x52, 0x69, 0xac, 0x15, 0x43, 0xe6, 0x17, 0xe0, 0xbe,
	0x43, 0xdb, 0x32, 0xc3, 0x33, 0xad, 0x78, 0x1e, 0xf6, 0x03, 0x6b, 0x45, 0xf3, 0x0c, 0xda, 0x21,
	0x5a, 0x08, 0x81, 0x94, 0xa1, 0x07, 0x4c, 0x97, 0xdb, 0xe7, 0xd4, 0xc7, 0x82, 0x5c, 0x86, 0xeb,
	0xd3, 0x27, 0x92, 0x96, 0x67, 0x72, 0x5f, 0xac, 0x7d, 0x6a, 0xa7, 0x75, 0x18, 0x65, 0x84, 0xa8,
	0xa4, 0xc1, 0x63, 0x85, 0x21, 0x22, 0x69, 0x38, 0x75, 0x2e, 0x97, 0x58, 0xb0, 0x2b, 0x5a, 0x9e,
	0x1d, 0x9e, 0xba, 0xd8, 0x02, 0xd1, 0xac, 0xcb, 0xe5, 0x31, 0xbb, 0xa2, 0x66, 0x1b, 0x80, 0x36,
	0x73, 0xf0, 0x09, 0x51, 0x63, 0x37, 0xa7, 0x24, 0xee, 0xe5, 0x96, 0xb8, 0xa8, 0xf9, 0x53, 0x26,
	0x88, 0x0a, 0x6d, 0xe6, 0x1c, 0xe8, 0xcf, 0x3f, 0x1b, 0xa0, 0x38, 0x34, 0x78, 0x39, 0x66, 0xee,
	0x32, 0xbe, 0xdf, 0x61, 0xca, 0x98, 0x75, 0x4e, 0x78, 0x74, 0xbf, 0x6b, 0x77, 0xb8, 0x1d, 0x99,
	0x31, 0xbf, 0xfd, 0x72, 0x27, 0xa4, 0x10, 0x2d, 0x28, 0x24, 0xac, 0x62, 0x33, 0xfc, 0xfe, 0x1a,
	0x98, 0xbb, 0x9e, 0xd7, 0xe2, 0xfb, 0xb4, 0xc3, 0x2f, 0x44, 0xfe, 0xbd, 0xb4, 0x0d, 0x0a, 0xf1,
	0xc0, 0x0a, 0xa5, 0x78, 0xaa, 0xb1, 0x9c, 0x5e, 0xd1, 0xc4, 0x04, 0xd1, 0x5c, 0xb4, 0x01, 0x04,
	0xfc, 0xc5, 0x00, 0x8b, 0xcf, 0x98, 0x90, 0xdc, 0x67, 0x36, 0x71, 0x77, 0xbb, 0x76, 0xf8, 0xa8,
	0xe5, 0x2a, 0x55, 0x49, 0xf3, 0x4a, 0x8e, 0x89, 0x3e, 0x7d, 0xc7, 0x67, 0xaa, 0xc5, 0xa3, 0x68,
	0xf1, 0x26, 0x5c, 0xef, 0x07, 0xd6, 0x6a, 0x56, 0x6a, 0x4a, 0x19, 0xaf, 0xc1, 0xe4, 0x0c, 0x7c,
	0x13, 0x3f, 0x49, 0xc3, 0x34, 0xe6, 0x0e, 0x28, 0x44, 0xa7, 0x9a, 0xb1, 0xfc, 0x95, 0x74, 0x5e,
	0x22, 0x93, 0x4a, 0x21, 0xf5, 0x33, 0x9f, 0x82, 0x8f, 0x74, 0x4c, 0x47, 0x95, 0x5e, 0xa5, 0x50,
	0x68, 0xac, 0xf6, 0x03, 0x6b, 0x29, 0xab, 0x48, 0x5b, 0x21, 0x9a, 0x57, 0x5f, 0x75, 0x9b, 0xe0,
	0xb5, 0x01, 0xd6, 0x93, 0xee, 0x47, 0x62, 0xfe, 0xdb, 0xae, 0xfb, 0xc1, 0x00, 0x0f, 0x92, 0x17,
	0x78, 0x80, 0x29, 0xaa, 0xe9, 0xe7, 0x77, 0x78, 0xfa, 0x47, 0x15, 0x34, 0x3e, 0x8b, 0xc6, 0xf0,
	0xd1, 0xe8, 0x3f, 0x00, 0x71, 0x3d, 0x5c, 0xe5, 0x0e, 0xd1, 0x98, 0xf8, 0xf0, 0xed, 0x24, 0x58,
	0xff, 0x40, 0x88, 0xdc, 0x4f, 0xcf, 0x21, 0x30, 0x99, 0xc0, 0xf1, 0x72, 0x4c, 0x27, 0xc7, 0xa8,
	0xce, 0x65, 0x37, 0xf1, 0xa8, 0x0f, 0x44, 0x25, 0x26, 0x8e, 0x35, 0x16, 0x8f, 0x6b, 0x03, 0x14,
	0x99, 0xc0, 0x6a, 0x43, 0xc6, 0x4c, 0x93, 0x8a, 0x69, 0x2d, 0xbd, 0x7b, 0x43, 0x0e, 0x10, 0x2d,
	0x30, 0xb1, 0x4f, 0xdb, 0x32, 0xe6, 0x78, 0x06, 0x16, 0x59, 0x12, 0x04, 0x13, 0x5b, 0xb2, 0x4b,
	0xaa, 0xb6, 0xf9, 0x5c, 0x76, 0x9b, 0x8f, 0xb8, 0x40, 0x54, 0x64, 0xb1, 0x8e, 0x5d, 0x85, 0x98,
	0xaf, 0xa2, 0x26, 0x62, 0xde, 0x95, 0x98, 0xfb, 0xc4, 0x76, 0x29, 0xf6, 0x7c, 0x66, 0xd3, 0x72,
	0x51, 0xd1, 0x3d, 0xea, 0x07, 0xd6, 0x66, 0xb6, 0x30, 0xc3, 0x7e, 0x10, 0x2d, 0x29, 0xc3, 0x51,
	0x57, 0x1e, 0x29, 0xf8, 0x65, 0x88, 0x86, 0x59, 0xa6, 0xfe, 0x9a, 0xb0, 0xa4, 0x2a, 0xbd, 0x36,
	0xbc, 0x61, 0x12, 0x87, 0x78, 0xc3, 0x1c, 0x75, 0xa5, 0xe2, 0x68, 0x3c, 0x7f, 0x77, 0x5d, 0x31,
	0xde, 0x5f, 0x57, 0x8c, 0xbf, 0xae, 0x2b, 0xc6, 0xf7, 0x37, 0x95, 0x89, 0xf7, 0x37, 0x95, 0x89,
	0x3f, 0x6e, 0x2a, 0x13, 0x5f, 0xed, 0x0c, 0x6c, 0xde, 0x70, 0xc8, 0x1e, 0xf3, 0x93, 0x13, 0x66,
	0x33, 0xe2, 0x46, 0xdf, 0xeb, 0xd9, 0x9f, 0x5c, 0x6a, 0x15, 0xb7, 0x67, 0xd4, 0xef, 0xa6, 0x9d,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x35, 0xb7, 0x36, 0x93, 0x0d, 0x00, 0x00,
}

func (m *CollectorData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CollectorData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CollectorData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.LiquidationRewardsCollected.Size()
		i -= size
		if _, err := m.LiquidationRewardsCollected.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCollector(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.CollectedOpeningFee.Size()
		i -= size
		if _, err := m.CollectedOpeningFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCollector(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.CollectedClosingFee.Size()
		i -= size
		if _, err := m.CollectedClosingFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCollector(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.CollectedStabilityFee.Size()
		i -= size
		if _, err := m.CollectedStabilityFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCollector(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *NetFeeCollectedData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NetFeeCollectedData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NetFeeCollectedData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AssetIdToFeeCollected) > 0 {
		for iNdEx := len(m.AssetIdToFeeCollected) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AssetIdToFeeCollected[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCollector(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.AppId != 0 {
		i = encodeVarintCollector(dAtA, i, uint64(m.AppId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AssetIdToFeeCollected) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AssetIdToFeeCollected) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AssetIdToFeeCollected) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.NetFeesCollected.Size()
		i -= size
		if _, err := m.NetFeesCollected.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCollector(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.AssetId != 0 {
		i = encodeVarintCollector(dAtA, i, uint64(m.AssetId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AppIdToAssetCollectorMapping) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AppIdToAssetCollectorMapping) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AppIdToAssetCollectorMapping) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AssetCollector) > 0 {
		for iNdEx := len(m.AssetCollector) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AssetCollector[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCollector(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.AppId != 0 {
		i = encodeVarintCollector(dAtA, i, uint64(m.AppId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AssetIdCollectorMapping) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AssetIdCollectorMapping) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AssetIdCollectorMapping) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Collector.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintCollector(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.AssetId != 0 {
		i = encodeVarintCollector(dAtA, i, uint64(m.AssetId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CollectorLookupTable) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CollectorLookupTable) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CollectorLookupTable) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.BidFactor.Size()
		i -= size
		if _, err := m.BidFactor.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCollector(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	if m.LotSize != 0 {
		i = encodeVarintCollector(dAtA, i, uint64(m.LotSize))
		i--
		dAtA[i] = 0x38
	}
	{
		size := m.LockerSavingRate.Size()
		i -= size
		if _, err := m.LockerSavingRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCollector(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.DebtThreshold != 0 {
		i = encodeVarintCollector(dAtA, i, uint64(m.DebtThreshold))
		i--
		dAtA[i] = 0x28
	}
	if m.SurplusThreshold != 0 {
		i = encodeVarintCollector(dAtA, i, uint64(m.SurplusThreshold))
		i--
		dAtA[i] = 0x20
	}
	if m.SecondaryAssetId != 0 {
		i = encodeVarintCollector(dAtA, i, uint64(m.SecondaryAssetId))
		i--
		dAtA[i] = 0x18
	}
	if m.CollectorAssetId != 0 {
		i = encodeVarintCollector(dAtA, i, uint64(m.CollectorAssetId))
		i--
		dAtA[i] = 0x10
	}
	if m.AppId != 0 {
		i = encodeVarintCollector(dAtA, i, uint64(m.AppId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CollectorLookup) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CollectorLookup) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CollectorLookup) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AssetRateInfo) > 0 {
		for iNdEx := len(m.AssetRateInfo) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AssetRateInfo[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCollector(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.AppId != 0 {
		i = encodeVarintCollector(dAtA, i, uint64(m.AppId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AppToDenomsMapping) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AppToDenomsMapping) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AppToDenomsMapping) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AssetIds) > 0 {
		dAtA3 := make([]byte, len(m.AssetIds)*10)
		var j2 int
		for _, num := range m.AssetIds {
			for num >= 1<<7 {
				dAtA3[j2] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j2++
			}
			dAtA3[j2] = uint8(num)
			j2++
		}
		i -= j2
		copy(dAtA[i:], dAtA3[:j2])
		i = encodeVarintCollector(dAtA, i, uint64(j2))
		i--
		dAtA[i] = 0x12
	}
	if m.AppId != 0 {
		i = encodeVarintCollector(dAtA, i, uint64(m.AppId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *HistoricalAuction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HistoricalAuction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HistoricalAuction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AssetToAuction) > 0 {
		for iNdEx := len(m.AssetToAuction) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AssetToAuction[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCollector(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.AppId != 0 {
		i = encodeVarintCollector(dAtA, i, uint64(m.AppId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AssetToAuctionMapping) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AssetToAuctionMapping) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AssetToAuctionMapping) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AssetDenoms) > 0 {
		for iNdEx := len(m.AssetDenoms) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AssetDenoms[iNdEx])
			copy(dAtA[i:], m.AssetDenoms[iNdEx])
			i = encodeVarintCollector(dAtA, i, uint64(len(m.AssetDenoms[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.AuctionId != 0 {
		i = encodeVarintCollector(dAtA, i, uint64(m.AuctionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CollectorAuctionLookupTable) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CollectorAuctionLookupTable) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CollectorAuctionLookupTable) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AssetIdToAuctionLookup) > 0 {
		for iNdEx := len(m.AssetIdToAuctionLookup) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AssetIdToAuctionLookup[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCollector(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.AppId != 0 {
		i = encodeVarintCollector(dAtA, i, uint64(m.AppId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AssetIdToAuctionLookupTable) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AssetIdToAuctionLookupTable) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AssetIdToAuctionLookupTable) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AssetOutPrice != 0 {
		i = encodeVarintCollector(dAtA, i, uint64(m.AssetOutPrice))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.AssetOutOraclePrice {
		i--
		if m.AssetOutOraclePrice {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x78
	}
	if m.IsAuctionActive {
		i--
		if m.IsAuctionActive {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.IsDebtAuction {
		i--
		if m.IsDebtAuction {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.IsSurplusAuction {
		i--
		if m.IsSurplusAuction {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.AssetId != 0 {
		i = encodeVarintCollector(dAtA, i, uint64(m.AssetId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintCollector(dAtA []byte, offset int, v uint64) int {
	offset -= sovCollector(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CollectorData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CollectedStabilityFee.Size()
	n += 1 + l + sovCollector(uint64(l))
	l = m.CollectedClosingFee.Size()
	n += 1 + l + sovCollector(uint64(l))
	l = m.CollectedOpeningFee.Size()
	n += 1 + l + sovCollector(uint64(l))
	l = m.LiquidationRewardsCollected.Size()
	n += 1 + l + sovCollector(uint64(l))
	return n
}

func (m *NetFeeCollectedData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AppId != 0 {
		n += 1 + sovCollector(uint64(m.AppId))
	}
	if len(m.AssetIdToFeeCollected) > 0 {
		for _, e := range m.AssetIdToFeeCollected {
			l = e.Size()
			n += 1 + l + sovCollector(uint64(l))
		}
	}
	return n
}

func (m *AssetIdToFeeCollected) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AssetId != 0 {
		n += 1 + sovCollector(uint64(m.AssetId))
	}
	l = m.NetFeesCollected.Size()
	n += 1 + l + sovCollector(uint64(l))
	return n
}

func (m *AppIdToAssetCollectorMapping) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AppId != 0 {
		n += 1 + sovCollector(uint64(m.AppId))
	}
	if len(m.AssetCollector) > 0 {
		for _, e := range m.AssetCollector {
			l = e.Size()
			n += 1 + l + sovCollector(uint64(l))
		}
	}
	return n
}

func (m *AssetIdCollectorMapping) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AssetId != 0 {
		n += 1 + sovCollector(uint64(m.AssetId))
	}
	l = m.Collector.Size()
	n += 1 + l + sovCollector(uint64(l))
	return n
}

func (m *CollectorLookupTable) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AppId != 0 {
		n += 1 + sovCollector(uint64(m.AppId))
	}
	if m.CollectorAssetId != 0 {
		n += 1 + sovCollector(uint64(m.CollectorAssetId))
	}
	if m.SecondaryAssetId != 0 {
		n += 1 + sovCollector(uint64(m.SecondaryAssetId))
	}
	if m.SurplusThreshold != 0 {
		n += 1 + sovCollector(uint64(m.SurplusThreshold))
	}
	if m.DebtThreshold != 0 {
		n += 1 + sovCollector(uint64(m.DebtThreshold))
	}
	l = m.LockerSavingRate.Size()
	n += 1 + l + sovCollector(uint64(l))
	if m.LotSize != 0 {
		n += 1 + sovCollector(uint64(m.LotSize))
	}
	l = m.BidFactor.Size()
	n += 1 + l + sovCollector(uint64(l))
	return n
}

func (m *CollectorLookup) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AppId != 0 {
		n += 1 + sovCollector(uint64(m.AppId))
	}
	if len(m.AssetRateInfo) > 0 {
		for _, e := range m.AssetRateInfo {
			l = e.Size()
			n += 1 + l + sovCollector(uint64(l))
		}
	}
	return n
}

func (m *AppToDenomsMapping) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AppId != 0 {
		n += 1 + sovCollector(uint64(m.AppId))
	}
	if len(m.AssetIds) > 0 {
		l = 0
		for _, e := range m.AssetIds {
			l += sovCollector(uint64(e))
		}
		n += 1 + sovCollector(uint64(l)) + l
	}
	return n
}

func (m *HistoricalAuction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AppId != 0 {
		n += 1 + sovCollector(uint64(m.AppId))
	}
	if len(m.AssetToAuction) > 0 {
		for _, e := range m.AssetToAuction {
			l = e.Size()
			n += 1 + l + sovCollector(uint64(l))
		}
	}
	return n
}

func (m *AssetToAuctionMapping) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AuctionId != 0 {
		n += 1 + sovCollector(uint64(m.AuctionId))
	}
	if len(m.AssetDenoms) > 0 {
		for _, s := range m.AssetDenoms {
			l = len(s)
			n += 1 + l + sovCollector(uint64(l))
		}
	}
	return n
}

func (m *CollectorAuctionLookupTable) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AppId != 0 {
		n += 1 + sovCollector(uint64(m.AppId))
	}
	if len(m.AssetIdToAuctionLookup) > 0 {
		for _, e := range m.AssetIdToAuctionLookup {
			l = e.Size()
			n += 1 + l + sovCollector(uint64(l))
		}
	}
	return n
}

func (m *AssetIdToAuctionLookupTable) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AssetId != 0 {
		n += 1 + sovCollector(uint64(m.AssetId))
	}
	if m.IsSurplusAuction {
		n += 2
	}
	if m.IsDebtAuction {
		n += 2
	}
	if m.IsAuctionActive {
		n += 2
	}
	if m.AssetOutOraclePrice {
		n += 2
	}
	if m.AssetOutPrice != 0 {
		n += 2 + sovCollector(uint64(m.AssetOutPrice))
	}
	return n
}

func sovCollector(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCollector(x uint64) (n int) {
	return sovCollector(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CollectorData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCollector
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CollectorData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CollectorData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectedStabilityFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollector
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollector
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CollectedStabilityFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectedClosingFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollector
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollector
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CollectedClosingFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectedOpeningFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollector
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollector
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CollectedOpeningFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationRewardsCollected", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollector
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollector
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LiquidationRewardsCollected.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCollector(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCollector
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NetFeeCollectedData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCollector
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NetFeeCollectedData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NetFeeCollectedData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			m.AppId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetIdToFeeCollected", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCollector
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCollector
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetIdToFeeCollected = append(m.AssetIdToFeeCollected, AssetIdToFeeCollected{})
			if err := m.AssetIdToFeeCollected[len(m.AssetIdToFeeCollected)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCollector(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCollector
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AssetIdToFeeCollected) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCollector
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AssetIdToFeeCollected: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AssetIdToFeeCollected: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			m.AssetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetFeesCollected", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollector
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollector
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NetFeesCollected.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCollector(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCollector
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AppIdToAssetCollectorMapping) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCollector
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AppIdToAssetCollectorMapping: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AppIdToAssetCollectorMapping: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			m.AppId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetCollector", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCollector
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCollector
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetCollector = append(m.AssetCollector, AssetIdCollectorMapping{})
			if err := m.AssetCollector[len(m.AssetCollector)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCollector(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCollector
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AssetIdCollectorMapping) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCollector
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AssetIdCollectorMapping: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AssetIdCollectorMapping: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			m.AssetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Collector", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCollector
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCollector
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Collector.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCollector(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCollector
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CollectorLookupTable) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCollector
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CollectorLookupTable: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CollectorLookupTable: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			m.AppId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectorAssetId", wireType)
			}
			m.CollectorAssetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CollectorAssetId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecondaryAssetId", wireType)
			}
			m.SecondaryAssetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SecondaryAssetId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SurplusThreshold", wireType)
			}
			m.SurplusThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SurplusThreshold |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DebtThreshold", wireType)
			}
			m.DebtThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DebtThreshold |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockerSavingRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollector
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollector
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LockerSavingRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LotSize", wireType)
			}
			m.LotSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LotSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BidFactor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollector
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollector
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BidFactor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCollector(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCollector
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CollectorLookup) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCollector
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CollectorLookup: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CollectorLookup: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			m.AppId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetRateInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCollector
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCollector
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetRateInfo = append(m.AssetRateInfo, CollectorLookupTable{})
			if err := m.AssetRateInfo[len(m.AssetRateInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCollector(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCollector
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AppToDenomsMapping) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCollector
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AppToDenomsMapping: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AppToDenomsMapping: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			m.AppId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCollector
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.AssetIds = append(m.AssetIds, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCollector
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthCollector
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthCollector
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.AssetIds) == 0 {
					m.AssetIds = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCollector
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.AssetIds = append(m.AssetIds, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetIds", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCollector(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCollector
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HistoricalAuction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCollector
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HistoricalAuction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HistoricalAuction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			m.AppId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetToAuction", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCollector
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCollector
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetToAuction = append(m.AssetToAuction, &AssetToAuctionMapping{})
			if err := m.AssetToAuction[len(m.AssetToAuction)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCollector(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCollector
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AssetToAuctionMapping) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCollector
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AssetToAuctionMapping: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AssetToAuctionMapping: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionId", wireType)
			}
			m.AuctionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuctionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetDenoms", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollector
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollector
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetDenoms = append(m.AssetDenoms, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCollector(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCollector
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CollectorAuctionLookupTable) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCollector
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CollectorAuctionLookupTable: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CollectorAuctionLookupTable: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			m.AppId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetIdToAuctionLookup", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCollector
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCollector
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetIdToAuctionLookup = append(m.AssetIdToAuctionLookup, AssetIdToAuctionLookupTable{})
			if err := m.AssetIdToAuctionLookup[len(m.AssetIdToAuctionLookup)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCollector(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCollector
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AssetIdToAuctionLookupTable) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCollector
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AssetIdToAuctionLookupTable: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AssetIdToAuctionLookupTable: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			m.AssetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsSurplusAuction", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsSurplusAuction = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsDebtAuction", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsDebtAuction = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsAuctionActive", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsAuctionActive = bool(v != 0)
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetOutOraclePrice", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AssetOutOraclePrice = bool(v != 0)
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetOutPrice", wireType)
			}
			m.AssetOutPrice = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetOutPrice |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCollector(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCollector
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCollector(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCollector
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCollector
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCollector
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCollector
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCollector
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCollector        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCollector          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCollector = fmt.Errorf("proto: unexpected end of group")
)
