name: Starship E2E tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19
        id: go

      # Starship Infra setup
      # - Connects to k8s cluster with kubeconfig (digital ocean)
      # - Creates a new namespace based on the name (deleted in next step)
      # - Spins up the infra with the given config file
      # - Waits till all nodes are running (timeout 30m)
      # - Port forward all ports to localhost for next steps to connect
      - name: Setup Test infra
        id: starship-action
        uses: cosmology-tech/starship-action@0.2.13
        with:
          values: starship/configs/ci.yaml
          port-forward: true
          version: 0.1.42

      - name: Run Tests
        run: |
          cd starship/
          go mod tidy
          make test

      # Starship resource cleanup on cluster
      - name: Cleanup cluster
        if: always()
        run: |
          helm delete $DEVNET_NAME --debug --namespace $DEVNET_NAMESPACE --wait || true
          kubectl delete namespace $DEVNET_NAMESPACE --wait=true || true
        env:
          DEVNET_NAME: ${{ steps.starship-action.outputs.name }}
          DEVNET_NAMESPACE: ${{ steps.starship-action.outputs.namespace }}
