name: Run Gosec
on:
  push:
    branches:
      - feature/dev
      - development
  pull_request:
    branches:
      - feature/dev
      - development
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Run Gosec Security Scanner
        uses: informalsystems/gosec@master
        with:
          args: ./...
